/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * TerminateInstances request structure.
 * @class
 */
class TerminateInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance ID list. Maximum number of IDs: 100.</p>
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;

    }
}

/**
 * DescribeInstanceTypes response structure.
 * @class
 */
class DescribeInstanceTypesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Model quota list.
         * @type {Array.<InstanceTypeQuota> || null}
         */
        this.InstanceTypeQuotaSet = null;

        /**
         * Number of returned records.
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.InstanceTypeQuotaSet) {
            this.InstanceTypeQuotaSet = new Array();
            for (let z in params.InstanceTypeQuotaSet) {
                let obj = new InstanceTypeQuota();
                obj.deserialize(params.InstanceTypeQuotaSet[z]);
                this.InstanceTypeQuotaSet.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribePrivateNetworkInstances request structure.
 * @class
 */
class DescribePrivateNetworkInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Private network instance Id
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * New instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Pagination offset, default 0
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * Number of items per page. Default 20. Maximum 100.
         * @type {number || null}
         */
        this.Limit = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.Limit = 'Limit' in params ? params.Limit : null;

    }
}

/**
 * DescribePublicNetworkInstances response structure.
 * @class
 */
class DescribePublicNetworkInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Total number of public network instances
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * public network instance collection
         * @type {Array.<PublicNetworkInstanceInfo> || null}
         */
        this.PublicNetworkInstanceSet = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;

        if (params.PublicNetworkInstanceSet) {
            this.PublicNetworkInstanceSet = new Array();
            for (let z in params.PublicNetworkInstanceSet) {
                let obj = new PublicNetworkInstanceInfo();
                obj.deserialize(params.PublicNetworkInstanceSet[z]);
                this.PublicNetworkInstanceSet.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DeletePublicNetworkInstance request structure.
 * @class
 */
class DeletePublicNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;

    }
}

/**
 * CreateEdgeNodeService response structure.
 * @class
 */
class CreateEdgeNodeServiceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreateInstances request structure.
 * @class
 */
class CreateInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Availability zone code, such as ap-guangzhou-1.</p>
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * <p>Model specifications, such as BMS5.MEDIUM8.</p>
         * @type {string || null}
         */
        this.InstanceType = null;

        /**
         * <p>Private network instance ID in the format of net-xxx.</p>
         * @type {string || null}
         */
        this.PrivateNetworkId = null;

        /**
         * <p>Public network instance ID, in the format of net-xxx.</p>
         * @type {string || null}
         */
        this.PublicNetworkId = null;

        /**
         * <p>Instance name.</p>
         * @type {string || null}
         */
        this.InstanceName = null;

        /**
         * <p>Image ID, for example img-centos-7.9.</p>
         * @type {string || null}
         */
        this.ImageId = null;

        /**
         * <p>Specify the quantity. Default is 1. Maximum is 50.</p>
         * @type {number || null}
         */
        this.InstanceCount = null;

        /**
         * <p>Login password. Either it or SSHKey is required.</p>
         * @type {string || null}
         */
        this.Password = null;

        /**
         * <p>Public key string of the SSH key. Either this parameter or Password must be specified.</p>
         * @type {string || null}
         */
        this.SSHKey = null;

        /**
         * <p>Image version number. Only public images have the concept of version.</p>
         * @type {string || null}
         */
        this.VersionNumber = null;

        /**
         * <p>Whether to enable public IPv6, default false. Enabled, the system will allocate an additional IPv6 address after assigning an IPv4 address.</p>
         * @type {boolean || null}
         */
        this.EnableIpv6 = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.InstanceType = 'InstanceType' in params ? params.InstanceType : null;
        this.PrivateNetworkId = 'PrivateNetworkId' in params ? params.PrivateNetworkId : null;
        this.PublicNetworkId = 'PublicNetworkId' in params ? params.PublicNetworkId : null;
        this.InstanceName = 'InstanceName' in params ? params.InstanceName : null;
        this.ImageId = 'ImageId' in params ? params.ImageId : null;
        this.InstanceCount = 'InstanceCount' in params ? params.InstanceCount : null;
        this.Password = 'Password' in params ? params.Password : null;
        this.SSHKey = 'SSHKey' in params ? params.SSHKey : null;
        this.VersionNumber = 'VersionNumber' in params ? params.VersionNumber : null;
        this.EnableIpv6 = 'EnableIpv6' in params ? params.EnableIpv6 : null;

    }
}

/**
 * DescribeInstanceTypes request structure.
 * @class
 */
class DescribeInstanceTypesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Availability zone code, such as ap-guangzhou-1. If not passed, return models under the account in all AZs.
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * Pagination offset. Default value: 0.
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * Pagination size. Default value: 20. Maximum value: 100.
         * @type {number || null}
         */
        this.Limit = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.Limit = 'Limit' in params ? params.Limit : null;

    }
}

/**
 * Private network instance information
 * @class
 */
class PrivateNetworkInstanceInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Private network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Private network instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Network address.
         * @type {string || null}
         */
        this.Network = null;

        /**
         * Network mask
         * @type {number || null}
         */
        this.Mask = null;

        /**
         * Number of associated physical machines
         * @type {number || null}
         */
        this.ServerCount = null;

        /**
         * Available Ip quantity
         * @type {number || null}
         */
        this.AvailableIpCount = null;

        /**
         * Creation time.
         * @type {string || null}
         */
        this.CreatedAt = null;

        /**
         * Update time
         * @type {string || null}
         */
        this.UpdatedAt = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Network = 'Network' in params ? params.Network : null;
        this.Mask = 'Mask' in params ? params.Mask : null;
        this.ServerCount = 'ServerCount' in params ? params.ServerCount : null;
        this.AvailableIpCount = 'AvailableIpCount' in params ? params.AvailableIpCount : null;
        this.CreatedAt = 'CreatedAt' in params ? params.CreatedAt : null;
        this.UpdatedAt = 'UpdatedAt' in params ? params.UpdatedAt : null;

    }
}

/**
 * Public Ip information
 * @class
 */
class IpInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * 10.100.0.20
         * @type {string || null}
         */
        this.Ip = null;

        /**
         * epn-asdfghjkl
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * epm-asdfghjkl
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Unbound
         * @type {string || null}
         */
        this.State = null;

        /**
         * Ipv4
         * @type {string || null}
         */
        this.Type = null;

        /**
         * 2026-04-07T00:00:00
         * @type {string || null}
         */
        this.CreatedAt = null;

        /**
         * 2026-04-07T00:00:00
         * @type {string || null}
         */
        this.UpdatedAt = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Ip = 'Ip' in params ? params.Ip : null;
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.State = 'State' in params ? params.State : null;
        this.Type = 'Type' in params ? params.Type : null;
        this.CreatedAt = 'CreatedAt' in params ? params.CreatedAt : null;
        this.UpdatedAt = 'UpdatedAt' in params ? params.UpdatedAt : null;

    }
}

/**
 * DeletePublicNetworkInstance response structure.
 * @class
 */
class DeletePublicNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyPublicNetworkInstance response structure.
 * @class
 */
class ModifyPublicNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreatePrivateNetworkInstance request structure.
 * @class
 */
class CreatePrivateNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * New instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * The network address (host bits must be all 0s) must fall into one of the following RFC 1918 private ranges: `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`.
         * @type {string || null}
         */
        this.Network = null;

        /**
         * Mask digits. The upper limit is fixed at `28`, while the lower limit depends on the private segment it belongs to: `10.0.0.0/8` allows `8~28`, `172.16.0.0/12` allows `12~28`, `192.168.0.0/16` allows `16~28`. It must together form a valid network address with Network (host bits all set to 0).
         * @type {number || null}
         */
        this.Mask = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Network = 'Network' in params ? params.Network : null;
        this.Mask = 'Mask' in params ? params.Mask : null;

    }
}

/**
 * ModifyPrivateNetworkInstance request structure.
 * @class
 */
class ModifyPrivateNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Private network instance Id
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * New instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;

    }
}

/**
 * DescribeZones request structure.
 * @class
 */
class DescribeZonesRequest extends  AbstractModel {
    constructor(){
        super();

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

    }
}

/**
 * DescribePublicNetworkInstances request structure.
 * @class
 */
class DescribePublicNetworkInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Public network instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Pagination offset, default 0
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * Number of items per page. Default 20. Maximum 100.
         * @type {number || null}
         */
        this.Limit = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.Limit = 'Limit' in params ? params.Limit : null;

    }
}

/**
 * Account model quota information in the availability zone, including availability zone, model detail and quota quantity.
 * @class
 */
class InstanceTypeQuota extends  AbstractModel {
    constructor(){
        super();

        /**
         * Availability zone code.
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * Model specifications.
         * @type {string || null}
         */
        this.InstanceType = null;

        /**
         * Model family.
         * @type {string || null}
         */
        this.InstanceFamily = null;

        /**
         * Model family name
         * @type {string || null}
         */
        this.InstanceFamilyName = null;

        /**
         * Number of CPU cores.
         * @type {number || null}
         */
        this.CpuCores = null;

        /**
         * CPU type.
         * @type {string || null}
         */
        this.CpuType = null;

        /**
         * Memory size (GB).
         * @type {number || null}
         */
        this.MemoryGb = null;

        /**
         * System disk type.
         * @type {string || null}
         */
        this.SystemDiskType = null;

        /**
         * System disk size (GB).
         * @type {number || null}
         */
        this.SystemDiskSize = null;

        /**
         * Number of system disks.
         * @type {number || null}
         */
        this.SystemDiskCount = null;

        /**
         * Data disk type.
         * @type {string || null}
         */
        this.DataDiskType = null;

        /**
         * Data disk size (GB).
         * @type {number || null}
         */
        this.DataDiskSize = null;

        /**
         * Number of data disks.
         * @type {number || null}
         */
        this.DataDiskCount = null;

        /**
         * Second set of data disk types
         * @type {string || null}
         */
        this.SecondaryDataDiskType = null;

        /**
         * Data disk size of the second group (GB)
         * @type {number || null}
         */
        this.SecondaryDataDiskSize = null;

        /**
         * Number of data disks in the second set
         * @type {number || null}
         */
        this.SecondaryDataDiskCount = null;

        /**
         * Disk description string (backward compatibility).
         * @type {string || null}
         */
        this.DiskType = null;

        /**
         * Network interface type.
         * @type {string || null}
         */
        this.NetworkInterfaceType = null;

        /**
         * GPU type. Empty string if no GPU is available.
         * @type {string || null}
         */
        this.GpuType = null;

        /**
         * Quota quantity
         * @type {number || null}
         */
        this.Quota = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.InstanceType = 'InstanceType' in params ? params.InstanceType : null;
        this.InstanceFamily = 'InstanceFamily' in params ? params.InstanceFamily : null;
        this.InstanceFamilyName = 'InstanceFamilyName' in params ? params.InstanceFamilyName : null;
        this.CpuCores = 'CpuCores' in params ? params.CpuCores : null;
        this.CpuType = 'CpuType' in params ? params.CpuType : null;
        this.MemoryGb = 'MemoryGb' in params ? params.MemoryGb : null;
        this.SystemDiskType = 'SystemDiskType' in params ? params.SystemDiskType : null;
        this.SystemDiskSize = 'SystemDiskSize' in params ? params.SystemDiskSize : null;
        this.SystemDiskCount = 'SystemDiskCount' in params ? params.SystemDiskCount : null;
        this.DataDiskType = 'DataDiskType' in params ? params.DataDiskType : null;
        this.DataDiskSize = 'DataDiskSize' in params ? params.DataDiskSize : null;
        this.DataDiskCount = 'DataDiskCount' in params ? params.DataDiskCount : null;
        this.SecondaryDataDiskType = 'SecondaryDataDiskType' in params ? params.SecondaryDataDiskType : null;
        this.SecondaryDataDiskSize = 'SecondaryDataDiskSize' in params ? params.SecondaryDataDiskSize : null;
        this.SecondaryDataDiskCount = 'SecondaryDataDiskCount' in params ? params.SecondaryDataDiskCount : null;
        this.DiskType = 'DiskType' in params ? params.DiskType : null;
        this.NetworkInterfaceType = 'NetworkInterfaceType' in params ? params.NetworkInterfaceType : null;
        this.GpuType = 'GpuType' in params ? params.GpuType : null;
        this.Quota = 'Quota' in params ? params.Quota : null;

    }
}

/**
 * ModifyPublicNetworkInstance request structure.
 * @class
 */
class ModifyPublicNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * New instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;

    }
}

/**
 * ReleasePublicIp request structure.
 * @class
 */
class ReleasePublicIpRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID (route publishing mode is STATIC)
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Ip type to be released, enumeration value: ipv4, ipv6
         * @type {string || null}
         */
        this.Type = null;

        /**
         * List of Ip addresses to be released
         * @type {Array.<string> || null}
         */
        this.IpList = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.Type = 'Type' in params ? params.Type : null;
        this.IpList = 'IpList' in params ? params.IpList : null;

    }
}

/**
 * DescribeInstances response structure.
 * @class
 */
class DescribeInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance detail list</p>
         * @type {Array.<Instance> || null}
         */
        this.InstanceSet = null;

        /**
         * <p>Number of eligible instances.</p>
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.InstanceSet) {
            this.InstanceSet = new Array();
            for (let z in params.InstanceSet) {
                let obj = new Instance();
                obj.deserialize(params.InstanceSet[z]);
                this.InstanceSet.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreateEdgeNodeService request structure.
 * @class
 */
class CreateEdgeNodeServiceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Availability zone code, such as ap-guangzhou-1.
         * @type {string || null}
         */
        this.Zone = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Zone = 'Zone' in params ? params.Zone : null;

    }
}

/**
 * DescribeInstances request structure.
 * @class
 */
class DescribeInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance ID list for filtering by instance ID</p>
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

        /**
         * <p>Instance name, supports fuzzy matching.</p>
         * @type {string || null}
         */
        this.InstanceName = null;

        /**
         * <p>Availability zone code for filtering instances in the specified availability zone</p>
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * <p>Instance status list for status filtering. Available values: allocating, running, isolating, isolated, terminating, error.</p>
         * @type {Array.<string> || null}
         */
        this.InstanceStatus = null;

        /**
         * <p>Public network ID.</p>
         * @type {string || null}
         */
        this.PublicNetworkId = null;

        /**
         * <p>VPC ID.</p>
         * @type {string || null}
         */
        this.PrivateNetworkId = null;

        /**
         * <p>Public IPv4 address list, used for filtering instances by public IP address</p>
         * @type {Array.<string> || null}
         */
        this.PublicIps = null;

        /**
         * <p>Offset. Default value: 0.</p>
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * <p>Number of returned results. Default 20. Maximum 100.</p>
         * @type {number || null}
         */
        this.Limit = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;
        this.InstanceName = 'InstanceName' in params ? params.InstanceName : null;
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.InstanceStatus = 'InstanceStatus' in params ? params.InstanceStatus : null;
        this.PublicNetworkId = 'PublicNetworkId' in params ? params.PublicNetworkId : null;
        this.PrivateNetworkId = 'PrivateNetworkId' in params ? params.PrivateNetworkId : null;
        this.PublicIps = 'PublicIps' in params ? params.PublicIps : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.Limit = 'Limit' in params ? params.Limit : null;

    }
}

/**
 * Public network ip range info, including cidr and gateway ip
 * @class
 */
class PublicNetworkSegment extends  AbstractModel {
    constructor(){
        super();

        /**
         * Cidr of the subnet
         * @type {string || null}
         */
        this.Cidr = null;

        /**
         * Gateway Ip
         * @type {string || null}
         */
        this.Gateway = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Cidr = 'Cidr' in params ? params.Cidr : null;
        this.Gateway = 'Gateway' in params ? params.Gateway : null;

    }
}

/**
 * ReleasePublicIp response structure.
 * @class
 */
class ReleasePublicIpResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeZoneData response structure.
 * @class
 */
class DescribeZoneDataResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Stats, metrics inbw|outbw in Mbps
         * @type {Array.<SwitchData> || null}
         */
        this.Data = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Data) {
            this.Data = new Array();
            for (let z in params.Data) {
                let obj = new SwitchData();
                obj.deserialize(params.Data[z]);
                this.Data.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DeletePrivateNetworkInstance request structure.
 * @class
 */
class DeletePrivateNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Private network instance Id
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;

    }
}

/**
 * DescribePrivateNetworkInstances response structure.
 * @class
 */
class DescribePrivateNetworkInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Total number of private network instances
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * Private network instance set
         * @type {Array.<PrivateNetworkInstanceInfo> || null}
         */
        this.PrivateNetworkInstanceSet = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;

        if (params.PrivateNetworkInstanceSet) {
            this.PrivateNetworkInstanceSet = new Array();
            for (let z in params.PrivateNetworkInstanceSet) {
                let obj = new PrivateNetworkInstanceInfo();
                obj.deserialize(params.PrivateNetworkInstanceSet[z]);
                this.PrivateNetworkInstanceSet.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreatePrivateNetworkInstance response structure.
 * @class
 */
class CreatePrivateNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Private network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * TerminateInstances response structure.
 * @class
 */
class TerminateInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>List of instance IDs successfully terminated.</p>
         * @type {Array.<string> || null}
         */
        this.InstanceIdSet = null;

        /**
         * <p>List of instances with termination failed (returned when partially successful).</p>
         * @type {Array.<FailedInstance> || null}
         */
        this.FailedInstanceSet = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIdSet = 'InstanceIdSet' in params ? params.InstanceIdSet : null;

        if (params.FailedInstanceSet) {
            this.FailedInstanceSet = new Array();
            for (let z in params.FailedInstanceSet) {
                let obj = new FailedInstance();
                obj.deserialize(params.FailedInstanceSet[z]);
                this.FailedInstanceSet.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyInstanceAttribute request structure.
 * @class
 */
class ModifyInstanceAttributeRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * New instance name, 1-60 characters. Import at least one with NewPublicIp.
         * @type {string || null}
         */
        this.InstanceName = null;

        /**
         * New public IP address (select from available IP addresses of the public network instance bound to the instance). Provide at least one of this or InstanceName.
         * @type {string || null}
         */
        this.NewPublicIp = null;

        /**
         * IP type, ipv4 or ipv6. Default is ipv4. Valid only when NewPublicIp is specified.
         * @type {string || null}
         */
        this.IpType = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.InstanceName = 'InstanceName' in params ? params.InstanceName : null;
        this.NewPublicIp = 'NewPublicIp' in params ? params.NewPublicIp : null;
        this.IpType = 'IpType' in params ? params.IpType : null;

    }
}

/**
 * ApplyPublicIps request structure.
 * @class
 */
class ApplyPublicIpsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID (route publishing mode must be STATIC)
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Apply for an Ip quantity, minimum is 1
         * @type {number || null}
         */
        this.Count = null;

        /**
         * Applied Ip type, enumeration value: ipv4, ipv6
         * @type {string || null}
         */
        this.Type = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.Count = 'Count' in params ? params.Count : null;
        this.Type = 'Type' in params ? params.Type : null;

    }
}

/**
 * DescribePublicIps response structure.
 * @class
 */
class DescribePublicIpsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Total number of EIPs
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * Assigned public network IP address list
         * @type {Array.<IpInfo> || null}
         */
        this.IpInfoSet = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;

        if (params.IpInfoSet) {
            this.IpInfoSet = new Array();
            for (let z in params.IpInfoSet) {
                let obj = new IpInfo();
                obj.deserialize(params.IpInfoSet[z]);
                this.IpInfoSet.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DeletePrivateNetworkInstance response structure.
 * @class
 */
class DeletePrivateNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyPrivateNetworkInstance response structure.
 * @class
 */
class ModifyPrivateNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ApplyPublicIps response structure.
 * @class
 */
class ApplyPublicIpsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Assigned public network IP address list.
         * @type {Array.<string> || null}
         */
        this.IpList = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.IpList = 'IpList' in params ? params.IpList : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Switch data
 * @class
 */
class SwitchData extends  AbstractModel {
    constructor(){
        super();

        /**
         * UTC time
         * @type {string || null}
         */
        this.Time = null;

        /**
         * Statistical value
         * @type {number || null}
         */
        this.Value = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Time = 'Time' in params ? params.Time : null;
        this.Value = 'Value' in params ? params.Value : null;

    }
}

/**
 * CreateInstances response structure.
 * @class
 */
class CreateInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>List of successfully created instance IDs.</p>
         * @type {Array.<string> || null}
         */
        this.InstanceIdSet = null;

        /**
         * <p>Count of failed instances. This field is returned only when partially failed, not returned when all successful.</p>
         * @type {number || null}
         */
        this.FailedCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIdSet = 'InstanceIdSet' in params ? params.InstanceIdSet : null;
        this.FailedCount = 'FailedCount' in params ? params.FailedCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Describe physical machine instance information
 * @class
 */
class Instance extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <p>Instance name.</p>
         * @type {string || null}
         */
        this.InstanceName = null;

        /**
         * <p>Bound Physical Machine ID</p>
         * @type {string || null}
         */
        this.MachineId = null;

        /**
         * <p>Model specifications</p>
         * @type {string || null}
         */
        this.InstanceType = null;

        /**
         * <p>Availability zone code</p>
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * <p>Image ID.</p>
         * @type {string || null}
         */
        this.ImageId = null;

        /**
         * <p>Image version number</p>
         * @type {string || null}
         */
        this.VersionNumber = null;

        /**
         * <p>Instance status, value range: allocating, running, isolating, isolated, terminating, error.</p>
         * @type {string || null}
         */
        this.InstanceStatus = null;

        /**
         * <p>Operation status: normal, starting, stopping, stopped, rebooting.</p>
         * @type {string || null}
         */
        this.OperateStatus = null;

        /**
         * <p>VPC ID.</p>
         * @type {string || null}
         */
        this.PrivateNetworkId = null;

        /**
         * <p>Private IPv4 address</p>
         * @type {string || null}
         */
        this.PrivateIp = null;

        /**
         * <p>Private IPv6 address</p>
         * @type {string || null}
         */
        this.PrivateIpV6 = null;

        /**
         * <p>Public network ID.</p>
         * @type {string || null}
         */
        this.PublicNetworkId = null;

        /**
         * <p>Public IPv4 address</p>
         * @type {string || null}
         */
        this.PublicIp = null;

        /**
         * <p>Public IPv6 address</p>
         * @type {string || null}
         */
        this.PublicIpV6 = null;

        /**
         * <p>File System Type</p>
         * @type {string || null}
         */
        this.FileSystemType = null;

        /**
         * <p>Creation time, in the ISO 8601 standard format, using UTC time. Format: YYYY-MM-DDThh:mm:ssZ.</p>
         * @type {string || null}
         */
        this.CreatedTime = null;

        /**
         * <p>Instance family flag</p>
         * @type {string || null}
         */
        this.InstanceFamily = null;

        /**
         * <p>Model Family Name</p>
         * @type {string || null}
         */
        this.InstanceFamilyName = null;

        /**
         * <p>CPU Model</p>
         * @type {string || null}
         */
        this.CpuType = null;

        /**
         * <p>CPU cores.</p>
         * @type {number || null}
         */
        this.Cpu = null;

        /**
         * <p>Memory size.</p>
         * @type {number || null}
         */
        this.Memory = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.InstanceName = 'InstanceName' in params ? params.InstanceName : null;
        this.MachineId = 'MachineId' in params ? params.MachineId : null;
        this.InstanceType = 'InstanceType' in params ? params.InstanceType : null;
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.ImageId = 'ImageId' in params ? params.ImageId : null;
        this.VersionNumber = 'VersionNumber' in params ? params.VersionNumber : null;
        this.InstanceStatus = 'InstanceStatus' in params ? params.InstanceStatus : null;
        this.OperateStatus = 'OperateStatus' in params ? params.OperateStatus : null;
        this.PrivateNetworkId = 'PrivateNetworkId' in params ? params.PrivateNetworkId : null;
        this.PrivateIp = 'PrivateIp' in params ? params.PrivateIp : null;
        this.PrivateIpV6 = 'PrivateIpV6' in params ? params.PrivateIpV6 : null;
        this.PublicNetworkId = 'PublicNetworkId' in params ? params.PublicNetworkId : null;
        this.PublicIp = 'PublicIp' in params ? params.PublicIp : null;
        this.PublicIpV6 = 'PublicIpV6' in params ? params.PublicIpV6 : null;
        this.FileSystemType = 'FileSystemType' in params ? params.FileSystemType : null;
        this.CreatedTime = 'CreatedTime' in params ? params.CreatedTime : null;
        this.InstanceFamily = 'InstanceFamily' in params ? params.InstanceFamily : null;
        this.InstanceFamilyName = 'InstanceFamilyName' in params ? params.InstanceFamilyName : null;
        this.CpuType = 'CpuType' in params ? params.CpuType : null;
        this.Cpu = 'Cpu' in params ? params.Cpu : null;
        this.Memory = 'Memory' in params ? params.Memory : null;

    }
}

/**
 * Cross-regional AZ information after aggregating.
 * @class
 */
class ZoneInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * AZ ID.
         * @type {number || null}
         */
        this.ZoneId = null;

        /**
         * Availability zone code.
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * Chinese Name of Availability Zone.
         * @type {string || null}
         */
        this.ZoneName = null;

        /**
         * Availability zone English name.
         * @type {string || null}
         */
        this.ZoneNameEn = null;

        /**
         * Region code.
         * @type {string || null}
         */
        this.Region = null;

        /**
         * Area code.
         * @type {string || null}
         */
        this.Location = null;

        /**
         * Region name.
         * @type {string || null}
         */
        this.LocationName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.ZoneName = 'ZoneName' in params ? params.ZoneName : null;
        this.ZoneNameEn = 'ZoneNameEn' in params ? params.ZoneNameEn : null;
        this.Region = 'Region' in params ? params.Region : null;
        this.Location = 'Location' in params ? params.Location : null;
        this.LocationName = 'LocationName' in params ? params.LocationName : null;

    }
}

/**
 * ModifyInstanceAttribute response structure.
 * @class
 */
class ModifyInstanceAttributeResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeZones response structure.
 * @class
 */
class DescribeZonesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>AZ list of all regions.</p>
         * @type {Array.<ZoneInfo> || null}
         */
        this.ZoneSet = null;

        /**
         * <p>Total number of availability zones.</p>
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.ZoneSet) {
            this.ZoneSet = new Array();
            for (let z in params.ZoneSet) {
                let obj = new ZoneInfo();
                obj.deserialize(params.ZoneSet[z]);
                this.ZoneSet.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Public network instance info, including instance ID, availability zone ID, instance name, line, routing mode, etc.
 * @class
 */
class PublicNetworkInstanceInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Public network instance name
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Bandwidth, Unit: Mbps
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.Bandwidth = null;

        /**
         * Line information
         * @type {string || null}
         */
        this.Line = null;

        /**
         * Routing mode, enumeration value: STATIC, BGP, OSPF
         * @type {string || null}
         */
        this.RouteMode = null;

        /**
         * Number of Associated Physical Servers
         * @type {number || null}
         */
        this.ServerCount = null;

        /**
         * Applied Ipv4 quantity
         * @type {number || null}
         */
        this.Ipv4Count = null;

        /**
         * Number of applied Ipv6 addresses
         * @type {number || null}
         */
        this.Ipv6Count = null;

        /**
         * Associated Ipv4 subnet
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<PublicNetworkSegment> || null}
         */
        this.Ipv4CidrSet = null;

        /**
         * Associated Ipv6 segment
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<PublicNetworkSegment> || null}
         */
        this.Ipv6CidrSet = null;

        /**
         * Public network instance creation time
         * @type {string || null}
         */
        this.CreatedAt = null;

        /**
         * Public network instance last modified
         * @type {string || null}
         */
        this.UpdatedAt = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.Bandwidth = 'Bandwidth' in params ? params.Bandwidth : null;
        this.Line = 'Line' in params ? params.Line : null;
        this.RouteMode = 'RouteMode' in params ? params.RouteMode : null;
        this.ServerCount = 'ServerCount' in params ? params.ServerCount : null;
        this.Ipv4Count = 'Ipv4Count' in params ? params.Ipv4Count : null;
        this.Ipv6Count = 'Ipv6Count' in params ? params.Ipv6Count : null;

        if (params.Ipv4CidrSet) {
            this.Ipv4CidrSet = new Array();
            for (let z in params.Ipv4CidrSet) {
                let obj = new PublicNetworkSegment();
                obj.deserialize(params.Ipv4CidrSet[z]);
                this.Ipv4CidrSet.push(obj);
            }
        }

        if (params.Ipv6CidrSet) {
            this.Ipv6CidrSet = new Array();
            for (let z in params.Ipv6CidrSet) {
                let obj = new PublicNetworkSegment();
                obj.deserialize(params.Ipv6CidrSet[z]);
                this.Ipv6CidrSet.push(obj);
            }
        }
        this.CreatedAt = 'CreatedAt' in params ? params.CreatedAt : null;
        this.UpdatedAt = 'UpdatedAt' in params ? params.UpdatedAt : null;

    }
}

/**
 * CreatePublicNetworkInstance request structure.
 * @class
 */
class CreatePublicNetworkInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Availability zone ID.
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Public network instance name
         * @type {string || null}
         */
        this.NetworkInstanceName = null;

        /**
         * Network line
         * @type {string || null}
         */
        this.Line = null;

        /**
         * Routing mode
         * @type {string || null}
         */
        this.RouteMode = null;

        /**
         * Public network bandwidth (Mbps)
         * @type {number || null}
         */
        this.Bandwidth = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.NetworkInstanceName = 'NetworkInstanceName' in params ? params.NetworkInstanceName : null;
        this.Line = 'Line' in params ? params.Line : null;
        this.RouteMode = 'RouteMode' in params ? params.RouteMode : null;
        this.Bandwidth = 'Bandwidth' in params ? params.Bandwidth : null;

    }
}

/**
 * Failed instance info
 * @class
 */
class FailedInstance extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Error code.
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message.
         * @type {string || null}
         */
        this.ErrorMessage = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

    }
}

/**
 * CreatePublicNetworkInstance response structure.
 * @class
 */
class CreatePublicNetworkInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Public network instance ID
         * @type {string || null}
         */
        this.NetworkInstanceId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeZoneData request structure.
 * @class
 */
class DescribeZoneDataRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Availability zone id
         * @type {string || null}
         */
        this.Zone = null;

        /**
         * Metric name (inbw: inbound bandwidth, outbw: outbound bandwidth)
         * @type {string || null}
         */
        this.MetricName = null;

        /**
         * Start time (UTC time)
         * @type {string || null}
         */
        this.StartTime = null;

        /**
         * End time (UTC time), query up to 2 days.
         * @type {string || null}
         */
        this.EndTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Zone = 'Zone' in params ? params.Zone : null;
        this.MetricName = 'MetricName' in params ? params.MetricName : null;
        this.StartTime = 'StartTime' in params ? params.StartTime : null;
        this.EndTime = 'EndTime' in params ? params.EndTime : null;

    }
}

/**
 * DescribePublicIps request structure.
 * @class
 */
class DescribePublicIpsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Filter by public network instance ID (substring match, union of multiple values)
         * @type {Array.<string> || null}
         */
        this.NetworkInstanceId = null;

        /**
         * Filter by availability zone/IDC
         * @type {string || null}
         */
        this.ZoneId = null;

        /**
         * Filter by IP (substring match, union of multiple values)
         * @type {Array.<string> || null}
         */
        this.Ip = null;

        /**
         * Filter by status, available values: `InUse`, `Unbound` (multiple values are combined with OR)
         * @type {Array.<string> || null}
         */
        this.State = null;

        /**
         * Filter by IP version. Available values: `Ipv4`, `Ipv6` (multiple values are combined).
         * @type {Array.<string> || null}
         */
        this.Type = null;

        /**
         * Sort by creation time, available values: `asc`, `desc` (default `desc`)
         * @type {string || null}
         */
        this.OrderByCreateTime = null;

        /**
         * Sort by update time, available values: `asc`, `desc` (priority is higher than sort by creation time)
         * @type {string || null}
         */
        this.OrderByUpdateTime = null;

        /**
         * Pagination offset, default 0
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * Number of items per page. Default 20. Maximum 100.
         * @type {number || null}
         */
        this.Limit = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.NetworkInstanceId = 'NetworkInstanceId' in params ? params.NetworkInstanceId : null;
        this.ZoneId = 'ZoneId' in params ? params.ZoneId : null;
        this.Ip = 'Ip' in params ? params.Ip : null;
        this.State = 'State' in params ? params.State : null;
        this.Type = 'Type' in params ? params.Type : null;
        this.OrderByCreateTime = 'OrderByCreateTime' in params ? params.OrderByCreateTime : null;
        this.OrderByUpdateTime = 'OrderByUpdateTime' in params ? params.OrderByUpdateTime : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.Limit = 'Limit' in params ? params.Limit : null;

    }
}

module.exports = {
    TerminateInstancesRequest: TerminateInstancesRequest,
    DescribeInstanceTypesResponse: DescribeInstanceTypesResponse,
    DescribePrivateNetworkInstancesRequest: DescribePrivateNetworkInstancesRequest,
    DescribePublicNetworkInstancesResponse: DescribePublicNetworkInstancesResponse,
    DeletePublicNetworkInstanceRequest: DeletePublicNetworkInstanceRequest,
    CreateEdgeNodeServiceResponse: CreateEdgeNodeServiceResponse,
    CreateInstancesRequest: CreateInstancesRequest,
    DescribeInstanceTypesRequest: DescribeInstanceTypesRequest,
    PrivateNetworkInstanceInfo: PrivateNetworkInstanceInfo,
    IpInfo: IpInfo,
    DeletePublicNetworkInstanceResponse: DeletePublicNetworkInstanceResponse,
    ModifyPublicNetworkInstanceResponse: ModifyPublicNetworkInstanceResponse,
    CreatePrivateNetworkInstanceRequest: CreatePrivateNetworkInstanceRequest,
    ModifyPrivateNetworkInstanceRequest: ModifyPrivateNetworkInstanceRequest,
    DescribeZonesRequest: DescribeZonesRequest,
    DescribePublicNetworkInstancesRequest: DescribePublicNetworkInstancesRequest,
    InstanceTypeQuota: InstanceTypeQuota,
    ModifyPublicNetworkInstanceRequest: ModifyPublicNetworkInstanceRequest,
    ReleasePublicIpRequest: ReleasePublicIpRequest,
    DescribeInstancesResponse: DescribeInstancesResponse,
    CreateEdgeNodeServiceRequest: CreateEdgeNodeServiceRequest,
    DescribeInstancesRequest: DescribeInstancesRequest,
    PublicNetworkSegment: PublicNetworkSegment,
    ReleasePublicIpResponse: ReleasePublicIpResponse,
    DescribeZoneDataResponse: DescribeZoneDataResponse,
    DeletePrivateNetworkInstanceRequest: DeletePrivateNetworkInstanceRequest,
    DescribePrivateNetworkInstancesResponse: DescribePrivateNetworkInstancesResponse,
    CreatePrivateNetworkInstanceResponse: CreatePrivateNetworkInstanceResponse,
    TerminateInstancesResponse: TerminateInstancesResponse,
    ModifyInstanceAttributeRequest: ModifyInstanceAttributeRequest,
    ApplyPublicIpsRequest: ApplyPublicIpsRequest,
    DescribePublicIpsResponse: DescribePublicIpsResponse,
    DeletePrivateNetworkInstanceResponse: DeletePrivateNetworkInstanceResponse,
    ModifyPrivateNetworkInstanceResponse: ModifyPrivateNetworkInstanceResponse,
    ApplyPublicIpsResponse: ApplyPublicIpsResponse,
    SwitchData: SwitchData,
    CreateInstancesResponse: CreateInstancesResponse,
    Instance: Instance,
    ZoneInfo: ZoneInfo,
    ModifyInstanceAttributeResponse: ModifyInstanceAttributeResponse,
    DescribeZonesResponse: DescribeZonesResponse,
    PublicNetworkInstanceInfo: PublicNetworkInstanceInfo,
    CreatePublicNetworkInstanceRequest: CreatePublicNetworkInstanceRequest,
    FailedInstance: FailedInstance,
    CreatePublicNetworkInstanceResponse: CreatePublicNetworkInstanceResponse,
    DescribeZoneDataRequest: DescribeZoneDataRequest,
    DescribePublicIpsRequest: DescribePublicIpsRequest,

}
