/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * CreateAlarm request structure.
 * @class
 */
class CreateAlarmRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Alarm rule name. specifies the name of the Alarm rule.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Product ID.
         * @type {number || null}
         */
        this.ProductId = null;

        /**
         * Quota ID.
         * @type {number || null}
         */
        this.QuotaId = null;

        /**
         * Alert metrics 1: quota usage 2: quota usage rate 3: remaining quota 4: remaining quota rate.
         * @type {number || null}
         */
        this.Metrics = null;

        /**
         * Specifies the Alarm threshold. value range: 0-100.
         * @type {number || null}
         */
        this.Threshold = null;

        /**
         * Alarm frequency.
         * @type {number || null}
         */
        this.Frequency = null;

        /**
         *   Member UIN
         * @type {number || null}
         */
        this.MemberUin = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;
        this.ProductId = 'ProductId' in params ? params.ProductId : null;
        this.QuotaId = 'QuotaId' in params ? params.QuotaId : null;
        this.Metrics = 'Metrics' in params ? params.Metrics : null;
        this.Threshold = 'Threshold' in params ? params.Threshold : null;
        this.Frequency = 'Frequency' in params ? params.Frequency : null;
        this.MemberUin = 'MemberUin' in params ? params.MemberUin : null;

    }
}

/**
 * CreateAlarm response structure.
 * @class
 */
class CreateAlarmResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

module.exports = {
    CreateAlarmRequest: CreateAlarmRequest,
    CreateAlarmResponse: CreateAlarmResponse,

}
