/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * Account Factory baseline configuration item.
 * @class
 */
class BaselineConfigItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the unique identifier for account factory baseline item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

        /**
         * Account factory baseline item configuration. different baseline item configuration parameters.
         * @type {string || null}
         */
        this.Configuration = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Identifier = 'Identifier' in params ? params.Identifier : null;
        this.Configuration = 'Configuration' in params ? params.Configuration : null;

    }
}

/**
 * UpdateAccountFactoryBaseline response structure.
 * @class
 */
class UpdateAccountFactoryBaselineResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Baseline item deployment task information list.
 * @class
 */
class BaselineStepTaskInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the unique Id of the task, which can only contain english letters and digits, and is a 16-character random string.
         * @type {string || null}
         */
        this.TaskId = null;

        /**
         * Specifies the unique identifier for the baseline feature item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

        /**
         * Specifies the member account uin of the applied baseline item.
         * @type {number || null}
         */
        this.MemberUin = null;

        /**
         * Baseline item application status. Running means the baseline item is in application. Success means the baseline item application is successful. Failed means the baseline item application failure. Pending means the baseline item is Pending application. Skipped means the baseline item is Skipped.
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrCode = null;

        /**
         * Error message
         * @type {string || null}
         */
        this.ErrMessage = null;

        /**
         * Baseline item deployment output.
         * @type {string || null}
         */
        this.Output = null;

        /**
         * Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
         * @type {string || null}
         */
        this.CreateTime = null;

        /**
         * Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
         * @type {string || null}
         */
        this.UpdateTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.TaskId = 'TaskId' in params ? params.TaskId : null;
        this.Identifier = 'Identifier' in params ? params.Identifier : null;
        this.MemberUin = 'MemberUin' in params ? params.MemberUin : null;
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrCode = 'ErrCode' in params ? params.ErrCode : null;
        this.ErrMessage = 'ErrMessage' in params ? params.ErrMessage : null;
        this.Output = 'Output' in params ? params.Output : null;
        this.CreateTime = 'CreateTime' in params ? params.CreateTime : null;
        this.UpdateTime = 'UpdateTime' in params ? params.UpdateTime : null;

    }
}

/**
 * ListAccountFactoryBaselineItems request structure.
 * @class
 */
class ListAccountFactoryBaselineItemsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Maximum number of returned records. value ranges from 0 to 200.
         * @type {number || null}
         */
        this.Limit = null;

        /**
         * Offset. valid values are equal to or greater than 0.
         * @type {number || null}
         */
        this.Offset = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Limit = 'Limit' in params ? params.Limit : null;
        this.Offset = 'Offset' in params ? params.Offset : null;

    }
}

/**
 * Dependency.
 * @class
 */
class DependsOnItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Dependency type. valid values: LandingZoneSetUp or AccountFactorySetUp. LandingZoneSetUp refers to the dependency of landingZone. AccountFactorySetUp refers to the dependency of account factory.
         * @type {string || null}
         */
        this.Type = null;

        /**
         * Specifies the unique identifier for the feature item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Type = 'Type' in params ? params.Type : null;
        this.Identifier = 'Identifier' in params ? params.Identifier : null;

    }
}

/**
 * BatchApplyAccountBaselines response structure.
 * @class
 */
class BatchApplyAccountBaselinesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * UpdateAccountFactoryBaseline request structure.
 * @class
 */
class UpdateAccountFactoryBaselineRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the baseline name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Baseline configuration. overwrite update. can be accessed through controlcenter:GetAccountFactoryBaseline to query existing baseline configuration. can be accessed through controlcenter:ListAccountFactoryBaselineItems to query supported baseline list.
         * @type {Array.<BaselineConfigItem> || null}
         */
        this.BaselineConfigItems = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;

        if (params.BaselineConfigItems) {
            this.BaselineConfigItems = new Array();
            for (let z in params.BaselineConfigItems) {
                let obj = new BaselineConfigItem();
                obj.deserialize(params.BaselineConfigItems[z]);
                this.BaselineConfigItems.push(obj);
            }
        }

    }
}

/**
 * ListDeployStepTasks request structure.
 * @class
 */
class ListDeployStepTasksRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the unique identifier for the feature item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

        /**
         * Maximum number of returned records. value ranges from 0 to 200.
         * @type {number || null}
         */
        this.Limit = null;

        /**
         * Offset. valid values are equal to or greater than 0.
         * @type {number || null}
         */
        this.Offset = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Identifier = 'Identifier' in params ? params.Identifier : null;
        this.Limit = 'Limit' in params ? params.Limit : null;
        this.Offset = 'Offset' in params ? params.Offset : null;

    }
}

/**
 * Account factory baseline item.
 * @class
 */
class AccountFactoryItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the unique identifier for account factory baseline item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

        /**
         * Baseline item name. specifies a unique name for the feature item. supports a combination of english letters, numbers, chinese characters, and symbols @, &, _, [, ], -. valid values: 1-25 chinese or english characters.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Baseline item english name. specifies a unique name for the baseline item. supports a combination of english letters, digits, spaces, and symbols @, &, _, [], -. valid values: 1-64 english characters.
         * @type {string || null}
         */
        this.NameEn = null;

        /**
         * Baseline item weight. the smaller the value, the higher the weight. value range equal to or greater than 0.
         * @type {number || null}
         */
        this.Weight = null;

        /**
         * Specifies whether the baseline item is required (1: required; 0: optional).
         * @type {number || null}
         */
        this.Required = null;

        /**
         * Baseline item dependency. value range of N depends on the count of other baseline items it relies on.
         * @type {Array.<DependsOnItem> || null}
         */
        this.DependsOn = null;

        /**
         * Baseline description, with a length of 2 to 256 english or chinese characters. it is empty by default.
         * @type {string || null}
         */
        this.Description = null;

        /**
         * Baseline item english description, with a length of 2 to 1024 english characters. it is empty by default.
         * @type {string || null}
         */
        this.DescriptionEn = null;

        /**
         * Baseline classification. length: 2-32 english or chinese characters. values cannot be empty.
         * @type {string || null}
         */
        this.Classify = null;

        /**
         * Baseline english classification, with a length of 2-64 english characters. cannot be empty.
         * @type {string || null}
         */
        this.ClassifyEn = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Identifier = 'Identifier' in params ? params.Identifier : null;
        this.Name = 'Name' in params ? params.Name : null;
        this.NameEn = 'NameEn' in params ? params.NameEn : null;
        this.Weight = 'Weight' in params ? params.Weight : null;
        this.Required = 'Required' in params ? params.Required : null;

        if (params.DependsOn) {
            this.DependsOn = new Array();
            for (let z in params.DependsOn) {
                let obj = new DependsOnItem();
                obj.deserialize(params.DependsOn[z]);
                this.DependsOn.push(obj);
            }
        }
        this.Description = 'Description' in params ? params.Description : null;
        this.DescriptionEn = 'DescriptionEn' in params ? params.DescriptionEn : null;
        this.Classify = 'Classify' in params ? params.Classify : null;
        this.ClassifyEn = 'ClassifyEn' in params ? params.ClassifyEn : null;

    }
}

/**
 * BatchApplyAccountBaselines request structure.
 * @class
 */
class BatchApplyAccountBaselinesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Member account UIN, which is also the UIN of the account to which the baseline is applied.
         * @type {Array.<number> || null}
         */
        this.MemberUinList = null;

        /**
         * List of baseline item configuration information.
         * @type {Array.<BaselineConfigItem> || null}
         */
        this.BaselineConfigItems = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.MemberUinList = 'MemberUinList' in params ? params.MemberUinList : null;

        if (params.BaselineConfigItems) {
            this.BaselineConfigItems = new Array();
            for (let z in params.BaselineConfigItems) {
                let obj = new BaselineConfigItem();
                obj.deserialize(params.BaselineConfigItems[z]);
                this.BaselineConfigItems.push(obj);
            }
        }

    }
}

/**
 * GetAccountFactoryBaseline response structure.
 * @class
 */
class GetAccountFactoryBaselineResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the uin of the main account to which the resource belongs.
         * @type {number || null}
         */
        this.OwnerUin = null;

        /**
         * Specifies the baseline item name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * List of baseline item configurations.
         * @type {Array.<BaselineInfoItem> || null}
         */
        this.BaselineConfigItems = null;

        /**
         * Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
         * @type {string || null}
         */
        this.CreateTime = null;

        /**
         * Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
         * @type {string || null}
         */
        this.UpdateTime = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.OwnerUin = 'OwnerUin' in params ? params.OwnerUin : null;
        this.Name = 'Name' in params ? params.Name : null;

        if (params.BaselineConfigItems) {
            this.BaselineConfigItems = new Array();
            for (let z in params.BaselineConfigItems) {
                let obj = new BaselineInfoItem();
                obj.deserialize(params.BaselineConfigItems[z]);
                this.BaselineConfigItems.push(obj);
            }
        }
        this.CreateTime = 'CreateTime' in params ? params.CreateTime : null;
        this.UpdateTime = 'UpdateTime' in params ? params.UpdateTime : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ListAccountFactoryBaselineItems response structure.
 * @class
 */
class ListAccountFactoryBaselineItemsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Account factory baseline list.
         * @type {Array.<AccountFactoryItem> || null}
         */
        this.BaselineItems = null;

        /**
         * Total quantity.
         * @type {number || null}
         */
        this.Total = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.BaselineItems) {
            this.BaselineItems = new Array();
            for (let z in params.BaselineItems) {
                let obj = new AccountFactoryItem();
                obj.deserialize(params.BaselineItems[z]);
                this.BaselineItems.push(obj);
            }
        }
        this.Total = 'Total' in params ? params.Total : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * GetAccountFactoryBaseline request structure.
 * @class
 */
class GetAccountFactoryBaselineRequest extends  AbstractModel {
    constructor(){
        super();

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

    }
}

/**
 * Account factory baseline information.
 * @class
 */
class BaselineInfoItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the unique identifier for account factory baseline item, can only contain english letters, digits, and @, ,._[]-:()()[]+=., with a length of 2-128 characters.
         * @type {string || null}
         */
        this.Identifier = null;

        /**
         * Account factory baseline item configuration. different baseline item configuration parameters.
         * @type {string || null}
         */
        this.Configuration = null;

        /**
         * Specifies the number of accounts for baseline applications.
         * @type {number || null}
         */
        this.ApplyCount = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Identifier = 'Identifier' in params ? params.Identifier : null;
        this.Configuration = 'Configuration' in params ? params.Configuration : null;
        this.ApplyCount = 'ApplyCount' in params ? params.ApplyCount : null;

    }
}

/**
 * ListDeployStepTasks response structure.
 * @class
 */
class ListDeployStepTasksResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Account factory baseline function application information list.
         * @type {Array.<BaselineStepTaskInfo> || null}
         */
        this.BaselineDeployStepTaskList = null;

        /**
         * Total quantity.
         * @type {number || null}
         */
        this.Total = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.BaselineDeployStepTaskList) {
            this.BaselineDeployStepTaskList = new Array();
            for (let z in params.BaselineDeployStepTaskList) {
                let obj = new BaselineStepTaskInfo();
                obj.deserialize(params.BaselineDeployStepTaskList[z]);
                this.BaselineDeployStepTaskList.push(obj);
            }
        }
        this.Total = 'Total' in params ? params.Total : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

module.exports = {
    BaselineConfigItem: BaselineConfigItem,
    UpdateAccountFactoryBaselineResponse: UpdateAccountFactoryBaselineResponse,
    BaselineStepTaskInfo: BaselineStepTaskInfo,
    ListAccountFactoryBaselineItemsRequest: ListAccountFactoryBaselineItemsRequest,
    DependsOnItem: DependsOnItem,
    BatchApplyAccountBaselinesResponse: BatchApplyAccountBaselinesResponse,
    UpdateAccountFactoryBaselineRequest: UpdateAccountFactoryBaselineRequest,
    ListDeployStepTasksRequest: ListDeployStepTasksRequest,
    AccountFactoryItem: AccountFactoryItem,
    BatchApplyAccountBaselinesRequest: BatchApplyAccountBaselinesRequest,
    GetAccountFactoryBaselineResponse: GetAccountFactoryBaselineResponse,
    ListAccountFactoryBaselineItemsResponse: ListAccountFactoryBaselineItemsResponse,
    GetAccountFactoryBaselineRequest: GetAccountFactoryBaselineRequest,
    BaselineInfoItem: BaselineInfoItem,
    ListDeployStepTasksResponse: ListDeployStepTasksResponse,

}
