/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * ModifyLibrary response structure.
 * @class
 */
class ModifyLibraryResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeLibraries response structure.
 * @class
 */
class DescribeLibrariesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Library list.
         * @type {Array.<Library> || null}
         */
        this.List = null;

        /**
         * Total number.
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.List) {
            this.List = new Array();
            for (let z in params.List) {
                let obj = new Library();
                obj.deserialize(params.List[z]);
                this.List.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SendSmsCode response structure.
 * @class
 */
class SendSmsCodeResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Describes official cloud disk instance information.
 * @class
 */
class Instance extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Dedicated domain name. if the instance has no dedicated domain name, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Domain = null;

        /**
         * Effective time.
         * @type {string || null}
         */
        this.EffectiveTime = null;

        /**
         * Expiration time. if the instance is pay-as-you-go or permanently valid, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ExpireTime = null;

        /**
         * Number of users. if the instance uses pay-as-you-go billing or has unlimited users, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.UserLimit = null;

        /**
         * Storage capacity in Bytes. this field is of String type due to precision limitations of numeric types. this property is null for pay-as-you-go instances or instances with unlimited storage capacity.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.StorageLimit = null;

        /**
         * Storage capacity in GB. if the instance uses pay-as-you-go billing or has unlimited storage capacity, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.StorageLimitGB = null;

        /**
         * Is expired isolation.
         * @type {boolean || null}
         */
        this.Isolated = null;

        /**
         * Renewal flag. 0: manual renewal; 1: automatic renewal; 2: non-renewal upon expiration.
         * @type {number || null}
         */
        this.AutoRenew = null;

        /**
         * Specifies the super administrator account. if no selection query is made for the instance-bound super administrator account or the current instance is not bound to a super administrator account, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.SuperAdminAccount = null;

        /**
         * In selected bucket mode, shows bucket usage.
         * @type {string || null}
         */
        this.Bucket = null;

        /**
         * Specifies the log bucket usage in selected mode.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.LogBucket = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.Domain = 'Domain' in params ? params.Domain : null;
        this.EffectiveTime = 'EffectiveTime' in params ? params.EffectiveTime : null;
        this.ExpireTime = 'ExpireTime' in params ? params.ExpireTime : null;
        this.UserLimit = 'UserLimit' in params ? params.UserLimit : null;
        this.StorageLimit = 'StorageLimit' in params ? params.StorageLimit : null;
        this.StorageLimitGB = 'StorageLimitGB' in params ? params.StorageLimitGB : null;
        this.Isolated = 'Isolated' in params ? params.Isolated : null;
        this.AutoRenew = 'AutoRenew' in params ? params.AutoRenew : null;
        this.SuperAdminAccount = 'SuperAdminAccount' in params ? params.SuperAdminAccount : null;
        this.Bucket = 'Bucket' in params ? params.Bucket : null;
        this.LogBucket = 'LogBucket' in params ? params.LogBucket : null;

    }
}

/**
 * Traffic package information.
 * @class
 */
class TrafficPackage extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the instance ID offset by the traffic package.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Dedicated domain name. if the instance has no dedicated domain name, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Domain = null;

        /**
         * Source type of the traffic package. valid values: 0 (purchase), 1 (complimentary).
         * @type {number || null}
         */
        this.Type = null;

        /**
         * Total traffic in Bytes. since the number type has precision limitations, this field is a String type.
         * @type {string || null}
         */
        this.Size = null;

        /**
         * Total traffic in GB.
         * @type {number || null}
         */
        this.SizeGB = null;

        /**
         * Remaining traffic in Bytes. this field is of String type due to precision limitations of numeric data types.
         * @type {string || null}
         */
        this.Remain = null;

        /**
         * Used traffic in Bytes. since the number type has precision limitations, this field is a String type.
         * @type {string || null}
         */
        this.Used = null;

        /**
         * Usage percentage. since the String type is used due to precision limitations of the number type, this field is of String type.
         * @type {string || null}
         */
        this.UsedPercentage = null;

        /**
         * Effective time, the order time of the traffic package.
         * @type {string || null}
         */
        this.EffectiveTime = null;

        /**
         * Expiration time, which is the expiration time of the offset instance. if the traffic package offsets a pay-as-you-go or permanently valid instance, this attribute is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ExpireTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.Domain = 'Domain' in params ? params.Domain : null;
        this.Type = 'Type' in params ? params.Type : null;
        this.Size = 'Size' in params ? params.Size : null;
        this.SizeGB = 'SizeGB' in params ? params.SizeGB : null;
        this.Remain = 'Remain' in params ? params.Remain : null;
        this.Used = 'Used' in params ? params.Used : null;
        this.UsedPercentage = 'UsedPercentage' in params ? params.UsedPercentage : null;
        this.EffectiveTime = 'EffectiveTime' in params ? params.EffectiveTime : null;
        this.ExpireTime = 'ExpireTime' in params ? params.ExpireTime : null;

    }
}

/**
 * DeleteLibrary request structure.
 * @class
 */
class DeleteLibraryRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library ID.
         * @type {string || null}
         */
        this.LibraryId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;

    }
}

/**
 * DescribeTrafficPackages request structure.
 * @class
 */
class DescribeTrafficPackagesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies one or more resource ids for querying, with a maximum of 100 per request.
         * @type {Array.<string> || null}
         */
        this.ResourceIds = null;

        /**
         * Page number, int, used in conjunction with PageSize. default value is 1.
         * @type {number || null}
         */
        this.PageNumber = null;

        /**
         * Number of items per page, integer, used in conjunction with PageNumber. default value is 20. maximum value is 100.
         * @type {number || null}
         */
        this.PageSize = null;

        /**
         * Specifies the column to sort.
         * @type {string || null}
         */
        this.OrderBy = null;

        /**
         * Sorting method.
         * @type {string || null}
         */
        this.OrderByType = null;

        /**
         * Specifies the source type filter criteria.
         * @type {number || null}
         */
        this.Type = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ResourceIds = 'ResourceIds' in params ? params.ResourceIds : null;
        this.PageNumber = 'PageNumber' in params ? params.PageNumber : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;
        this.OrderBy = 'OrderBy' in params ? params.OrderBy : null;
        this.OrderByType = 'OrderByType' in params ? params.OrderByType : null;
        this.Type = 'Type' in params ? params.Type : null;

    }
}

/**
 * DescribeTrafficPackages response structure.
 * @class
 */
class DescribeTrafficPackagesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Package list.
         * @type {Array.<TrafficPackage> || null}
         */
        this.List = null;

        /**
         * Total number.
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.List) {
            this.List = new Array();
            for (let z in params.List) {
                let obj = new TrafficPackage();
                obj.deserialize(params.List[z]);
                this.List.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeLibrarySecret request structure.
 * @class
 */
class DescribeLibrarySecretRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library ID.
         * @type {string || null}
         */
        this.LibraryId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;

    }
}

/**
 * DescribeLibrarySecret response structure.
 * @class
 */
class DescribeLibrarySecretResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the media library ID to query.
         * @type {string || null}
         */
        this.LibraryId = null;

        /**
         * Queried media library key.
         * @type {string || null}
         */
        this.LibrarySecret = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;
        this.LibrarySecret = 'LibrarySecret' in params ? params.LibrarySecret : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SendSmsCode request structure.
 * @class
 */
class SendSmsCodeRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Captcha target, currently supported: rebind super administrator account, BindSuperAdmin; trial version business upgrade, ChannelUpdateVerify.
         * @type {string || null}
         */
        this.Purpose = null;

        /**
         * Specifies the mobile number as the super admin account.
         * @type {string || null}
         */
        this.PhoneNumber = null;

        /**
         * Official cloud disk instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Specifies the country code of the mobile number that serves as the super administrator account. defaults to +86.
         * @type {string || null}
         */
        this.CountryCode = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Purpose = 'Purpose' in params ? params.Purpose : null;
        this.PhoneNumber = 'PhoneNumber' in params ? params.PhoneNumber : null;
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.CountryCode = 'CountryCode' in params ? params.CountryCode : null;

    }
}

/**
 * DescribeOfficialInstances request structure.
 * @class
 */
class DescribeOfficialInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies whether to query the super admin account bound to the instance. default value is false.
         * @type {boolean || null}
         */
        this.SuperAdminAccount = null;

        /**
         * Specifies one or more instance ids for querying, with a maximum of 100 per request.
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

        /**
         * Page number, int, used in conjunction with PageSize. default value is 1.
         * @type {number || null}
         */
        this.PageNumber = null;

        /**
         * Number of items per page, integer, used in conjunction with PageNumber. default value is 20. maximum value is 100.
         * @type {number || null}
         */
        this.PageSize = null;

        /**
         * Specifies the column to sort.
         * @type {string || null}
         */
        this.OrderBy = null;

        /**
         * Sorting method.
         * @type {string || null}
         */
        this.OrderByType = null;

        /**
         * Specifies the filter type for renewal management.
         * @type {number || null}
         */
        this.AutoRenew = null;

        /**
         * Specifies whether the super admin account is bound to a mobile number.
         * @type {boolean || null}
         */
        this.BindPhone = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SuperAdminAccount = 'SuperAdminAccount' in params ? params.SuperAdminAccount : null;
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;
        this.PageNumber = 'PageNumber' in params ? params.PageNumber : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;
        this.OrderBy = 'OrderBy' in params ? params.OrderBy : null;
        this.OrderByType = 'OrderByType' in params ? params.OrderByType : null;
        this.AutoRenew = 'AutoRenew' in params ? params.AutoRenew : null;
        this.BindPhone = 'BindPhone' in params ? params.BindPhone : null;

    }
}

/**
 * DescribeLibraries request structure.
 * @class
 */
class DescribeLibrariesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies one or more media library ids for querying, with a maximum of 100 per request.
         * @type {Array.<string> || null}
         */
        this.LibraryIds = null;

        /**
         * Page number, int, used in conjunction with PageSize. default value is 1.
         * @type {number || null}
         */
        this.PageNumber = null;

        /**
         * Number of items per page, integer, used in conjunction with PageNumber. default value is 20. maximum value is 100.
         * @type {number || null}
         */
        this.PageSize = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryIds = 'LibraryIds' in params ? params.LibraryIds : null;
        this.PageNumber = 'PageNumber' in params ? params.PageNumber : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;

    }
}

/**
 * Media library configuration item.
 * @class
 */
class LibraryExtension extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies whether it is a file type media library that can store any type of file (true) or a media type media library that can only store images and playable video types (false). defaults to false. cannot be modified once created.
         * @type {boolean || null}
         */
        this.IsFileLibrary = null;

        /**
         * true indicates a multi-tenant space media library, allowing the creation of multiple tenant spaces. false indicates a single-tenant space media library, where tenant spaces cannot be created and only the default single tenant space can be used. defaults to false. cannot be modified after the media library is created.
         * @type {boolean || null}
         */
        this.IsMultiSpace = null;

        /**
         * Specifies the storage type for files saved to cloud object storage. valid values: STANDARD, STANDARD_IA, INTELLIGENT_TIERING, MAZ_STANDARD, MAZ_STANDARD_IA, and MAZ_INTELLIGENT_TIERING. defaults to STANDARD. when using a multi-AZ bucket, MAZ_ prefixed storage types for multi-AZ are automatically used, otherwise non-MAZ_ prefixed storage types for non-multi-AZ are used. when specifying INTELLIGENT TIERING storage INTELLIGENT_TIERING or MAZ_INTELLIGENT_TIERING, the bucket must have INTELLIGENT TIERING storage enabled beforehand, otherwise failure will be returned. cannot be modified after the media library is created.
         * @type {string || null}
         */
        this.CosStorageClass = null;

        /**
         * Specifies whether the recycle bin feature is enabled. defaults to false.
         * @type {boolean || null}
         */
        this.UseRecycleBin = null;

        /**
         * Specifies the number of days to automatically delete items in the recycle bin when enabled, must not exceed 1095 (3 years). a value of 0 indicates no automatic deletion, defaults to 0. this property is null when the recycle bin is not enabled.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.AutoRemoveRecycledDays = null;

        /**
         * Whether to enable the file path search feature. is false by default.
         * @type {boolean || null}
         */
        this.EnableSearch = null;

        /**
         * Specifies whether to deny the configuration request when setting the space quota for a media library or tenant and the quota is less than the used storage capacity. is false by default.
         * @type {boolean || null}
         */
        this.DenyOnQuotaLessThanUsage = null;

        /**
         * Specifies whether the earlier version is enabled. defaults to false.
         * @type {boolean || null}
         */
        this.EnableFileHistory = null;

        /**
         * Specifies the maximum number of historical versions to retain for a single file when versioning is enabled, with a value range of 1 to 999. this property may be null when versioning is not enabled.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.FileHistoryCount = null;

        /**
         * Specifies the maximum days to retain earlier versions when versioning is enabled, with a value range of 0 to 999. when set to 0, it represents permanent retention. this property may be null when versioning is not enabled.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.FileHistoryExpireDay = null;

        /**
         * The maximum length of a directory or file name must not exceed 255, with a default value of 255. modifying this parameter will not affect existing directories or file names. if the value of this field is decreased, the length of existing directories or file names exceeding the target value does not change.
         * @type {number || null}
         */
        this.MaxDirFileNameLength = null;

        /**
         * Whether public read is enabled. once enabled, read operations require no access token. it is false by default. this property is supported only in single-tenant space media libraries. otherwise, it is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.IsPublicRead = null;

        /**
         * Specifies whether the multi-album feature is enabled for the media type media library. once enabled, first-level directories (albums) can be created, and media files can only be saved in these albums. unless enabled, albums cannot be created, and media files can only be saved in the root directory. defaults to false. this property is only supported for single-tenant space media type media libraries, otherwise it is null. cannot be modified after the media library is created.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.IsMultiAlbum = null;

        /**
         * Specifies whether the media library of the media type allows image uploads, set to true by default. this property is supported only for the media library of the media type in a single tenant space, otherwise it is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.AllowPhoto = null;

        /**
         * Specifies the allowed extensions when the media type media library allows photo uploads. empty array by default. at this point, it will automatically determine based on the MIME type corresponding to the file extension. this property is supported only for single-tenant space media type media libraries. otherwise, the property is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<string> || null}
         */
        this.AllowPhotoExtName = null;

        /**
         * Media type media library specifies whether video upload is allowed, set to true by default. this property is supported only in single tenant space media type media library, otherwise the property is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.AllowVideo = null;

        /**
         * Specifies the allowed extensions when the media type media library permits video uploads. the default is an empty array, at which point it will automatically determine based on the MIME type corresponding to the file extension. this property is supported only for single-tenant space media type media libraries, otherwise it is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<string> || null}
         */
        this.AllowVideoExtName = null;

        /**
         * Specifies the file extensions allowed in the file type media library, empty by default. at this point, all types of files are upload allowed. this property is supported only for the file type media library in a single tenant space, otherwise it is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<string> || null}
         */
        this.AllowFileExtName = null;

        /**
         * Specifies whether to perform sensitive content identification during image upload. the value is false by default. this property is supported only in the single-tenant space media library, otherwise it is null.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.RecognizeSensitiveContent = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.IsFileLibrary = 'IsFileLibrary' in params ? params.IsFileLibrary : null;
        this.IsMultiSpace = 'IsMultiSpace' in params ? params.IsMultiSpace : null;
        this.CosStorageClass = 'CosStorageClass' in params ? params.CosStorageClass : null;
        this.UseRecycleBin = 'UseRecycleBin' in params ? params.UseRecycleBin : null;
        this.AutoRemoveRecycledDays = 'AutoRemoveRecycledDays' in params ? params.AutoRemoveRecycledDays : null;
        this.EnableSearch = 'EnableSearch' in params ? params.EnableSearch : null;
        this.DenyOnQuotaLessThanUsage = 'DenyOnQuotaLessThanUsage' in params ? params.DenyOnQuotaLessThanUsage : null;
        this.EnableFileHistory = 'EnableFileHistory' in params ? params.EnableFileHistory : null;
        this.FileHistoryCount = 'FileHistoryCount' in params ? params.FileHistoryCount : null;
        this.FileHistoryExpireDay = 'FileHistoryExpireDay' in params ? params.FileHistoryExpireDay : null;
        this.MaxDirFileNameLength = 'MaxDirFileNameLength' in params ? params.MaxDirFileNameLength : null;
        this.IsPublicRead = 'IsPublicRead' in params ? params.IsPublicRead : null;
        this.IsMultiAlbum = 'IsMultiAlbum' in params ? params.IsMultiAlbum : null;
        this.AllowPhoto = 'AllowPhoto' in params ? params.AllowPhoto : null;
        this.AllowPhotoExtName = 'AllowPhotoExtName' in params ? params.AllowPhotoExtName : null;
        this.AllowVideo = 'AllowVideo' in params ? params.AllowVideo : null;
        this.AllowVideoExtName = 'AllowVideoExtName' in params ? params.AllowVideoExtName : null;
        this.AllowFileExtName = 'AllowFileExtName' in params ? params.AllowFileExtName : null;
        this.RecognizeSensitiveContent = 'RecognizeSensitiveContent' in params ? params.RecognizeSensitiveContent : null;

    }
}

/**
 * VerifySmsCode response structure.
 * @class
 */
class VerifySmsCodeResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyLibrary request structure.
 * @class
 */
class ModifyLibraryRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library ID.
         * @type {string || null}
         */
        this.LibraryId = null;

        /**
         * Media library name. up to 50 characters. leave empty to keep the current value.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Specifies the remark, up to 250 characters. leave it empty to keep the original value.
         * @type {string || null}
         */
        this.Remark = null;

        /**
         * Media library configuration item. some parameters cannot be changed after creation and only modify passed parameters. if this parameter is not passed, no configuration item will be modified.
         * @type {LibraryExtension || null}
         */
        this.LibraryExtension = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;
        this.Name = 'Name' in params ? params.Name : null;
        this.Remark = 'Remark' in params ? params.Remark : null;

        if (params.LibraryExtension) {
            let obj = new LibraryExtension();
            obj.deserialize(params.LibraryExtension)
            this.LibraryExtension = obj;
        }

    }
}

/**
 * DescribeOfficialOverview request structure.
 * @class
 */
class DescribeOfficialOverviewRequest extends  AbstractModel {
    constructor(){
        super();

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

    }
}

/**
 * DeleteLibrary response structure.
 * @class
 */
class DeleteLibraryResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeOfficialInstances response structure.
 * @class
 */
class DescribeOfficialInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance list
         * @type {Array.<Instance> || null}
         */
        this.List = null;

        /**
         * Total number.
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.List) {
            this.List = new Array();
            for (let z in params.List) {
                let obj = new Instance();
                obj.deserialize(params.List[z]);
                this.List.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * VerifySmsCode request structure.
 * @class
 */
class VerifySmsCodeRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Captcha target, currently supported: rebind super administrator account, BindSuperAdmin; trial version business upgrade verification, ChannelUpdateVerify.
         * @type {string || null}
         */
        this.Purpose = null;

        /**
         * Specifies the mobile number as the super admin account.
         * @type {string || null}
         */
        this.PhoneNumber = null;

        /**
         * Specifies the sms verification code.
         * @type {string || null}
         */
        this.Code = null;

        /**
         * Official cloud disk instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Specifies the country code of the mobile number that serves as the super administrator account. defaults to +86.
         * @type {string || null}
         */
        this.CountryCode = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Purpose = 'Purpose' in params ? params.Purpose : null;
        this.PhoneNumber = 'PhoneNumber' in params ? params.PhoneNumber : null;
        this.Code = 'Code' in params ? params.Code : null;
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.CountryCode = 'CountryCode' in params ? params.CountryCode : null;

    }
}

/**
 * CreateLibrary response structure.
 * @class
 */
class CreateLibraryResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library ID.
         * @type {string || null}
         */
        this.LibraryId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * PaaS service media library information.
 * @class
 */
class Library extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library ID.
         * @type {string || null}
         */
        this.LibraryId = null;

        /**
         * Specifies the friendly name of the media library.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Remarks.
         * @type {string || null}
         */
        this.Remark = null;

        /**
         * Specifies the COS storage bucket bound to the media library.
         * @type {string || null}
         */
        this.BucketName = null;

        /**
         * Specifies the region where the COS bucket bound to the media library is located.
         * @type {string || null}
         */
        this.BucketRegion = null;

        /**
         * Specifies the access domain of the business API for the media library.
         * @type {string || null}
         */
        this.AccessDomain = null;

        /**
         * Creation time of the media library.
         * @type {string || null}
         */
        this.CreationTime = null;

        /**
         * Media library configuration item.
         * @type {LibraryExtension || null}
         */
        this.LibraryExtension = null;

        /**
         * Media library amount in Bytes. since the number type has precision limitations, this field is a String type.
         * @type {string || null}
         */
        this.Size = null;

        /**
         * Number of media library directories. since the String type is used due to precision limitations of the number type, this field is of String type.
         * @type {string || null}
         */
        this.DirNum = null;

        /**
         * Number of files in the media library. since the String type is used due to precision limitations of the number type, this field is of String type.
         * @type {string || null}
         */
        this.FileNum = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.LibraryId = 'LibraryId' in params ? params.LibraryId : null;
        this.Name = 'Name' in params ? params.Name : null;
        this.Remark = 'Remark' in params ? params.Remark : null;
        this.BucketName = 'BucketName' in params ? params.BucketName : null;
        this.BucketRegion = 'BucketRegion' in params ? params.BucketRegion : null;
        this.AccessDomain = 'AccessDomain' in params ? params.AccessDomain : null;
        this.CreationTime = 'CreationTime' in params ? params.CreationTime : null;

        if (params.LibraryExtension) {
            let obj = new LibraryExtension();
            obj.deserialize(params.LibraryExtension)
            this.LibraryExtension = obj;
        }
        this.Size = 'Size' in params ? params.Size : null;
        this.DirNum = 'DirNum' in params ? params.DirNum : null;
        this.FileNum = 'FileNum' in params ? params.FileNum : null;

    }
}

/**
 * CreateLibrary request structure.
 * @class
 */
class CreateLibraryRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Media library name. up to 50 characters.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Specifies the remark, up to 250 characters.
         * @type {string || null}
         */
        this.Remark = null;

        /**
         * Specifies the full name of the bucket, which cannot be changed after creation. the current version no longer supports specified buckets.
         * @type {string || null}
         */
        this.BucketName = null;

        /**
         * Bucket location cannot be changed after creation. the current version no longer supports specifying bucket location.
         * @type {string || null}
         */
        this.BucketRegion = null;

        /**
         * Media library configuration item. some parameters cannot be changed after creation.
         * @type {LibraryExtension || null}
         */
        this.LibraryExtension = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;
        this.Remark = 'Remark' in params ? params.Remark : null;
        this.BucketName = 'BucketName' in params ? params.BucketName : null;
        this.BucketRegion = 'BucketRegion' in params ? params.BucketRegion : null;

        if (params.LibraryExtension) {
            let obj = new LibraryExtension();
            obj.deserialize(params.LibraryExtension)
            this.LibraryExtension = obj;
        }

    }
}

/**
 * DescribeOfficialOverview response structure.
 * @class
 */
class DescribeOfficialOverviewResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the instance count of cloud disks.
         * @type {number || null}
         */
        this.Quantity = null;

        /**
         * Indicates the total storage already used in Bytes. since the number type has precision limitations, this field is a String type.
         * @type {string || null}
         */
        this.Storage = null;

        /**
         * Total number of users already allocated and used.
         * @type {number || null}
         */
        this.UserCount = null;

        /**
         * Public network downstream traffic this month in Bytes. since the number type has precision limitations, this field is a String type.
         * @type {string || null}
         */
        this.InternetTraffic = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Quantity = 'Quantity' in params ? params.Quantity : null;
        this.Storage = 'Storage' in params ? params.Storage : null;
        this.UserCount = 'UserCount' in params ? params.UserCount : null;
        this.InternetTraffic = 'InternetTraffic' in params ? params.InternetTraffic : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

module.exports = {
    ModifyLibraryResponse: ModifyLibraryResponse,
    DescribeLibrariesResponse: DescribeLibrariesResponse,
    SendSmsCodeResponse: SendSmsCodeResponse,
    Instance: Instance,
    TrafficPackage: TrafficPackage,
    DeleteLibraryRequest: DeleteLibraryRequest,
    DescribeTrafficPackagesRequest: DescribeTrafficPackagesRequest,
    DescribeTrafficPackagesResponse: DescribeTrafficPackagesResponse,
    DescribeLibrarySecretRequest: DescribeLibrarySecretRequest,
    DescribeLibrarySecretResponse: DescribeLibrarySecretResponse,
    SendSmsCodeRequest: SendSmsCodeRequest,
    DescribeOfficialInstancesRequest: DescribeOfficialInstancesRequest,
    DescribeLibrariesRequest: DescribeLibrariesRequest,
    LibraryExtension: LibraryExtension,
    VerifySmsCodeResponse: VerifySmsCodeResponse,
    ModifyLibraryRequest: ModifyLibraryRequest,
    DescribeOfficialOverviewRequest: DescribeOfficialOverviewRequest,
    DeleteLibraryResponse: DeleteLibraryResponse,
    DescribeOfficialInstancesResponse: DescribeOfficialInstancesResponse,
    VerifySmsCodeRequest: VerifySmsCodeRequest,
    CreateLibraryResponse: CreateLibraryResponse,
    Library: Library,
    CreateLibraryRequest: CreateLibraryRequest,
    DescribeOfficialOverviewResponse: DescribeOfficialOverviewResponse,

}
