/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * Convert3DFormat request structure.
 * @class
 */
class Convert3DFormatRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * 3D file url address. model file size not greater than 60 mb
Supports fbx, obj, and glb format 3d file input
         * @type {string || null}
         */
        this.File3D = null;

        /**
         * Returns the 3D file format. valid values: 
STL, USDZ, FBX, MP4, GIF
Recommended input models below 50W, may timeout when selecting USDZ, MP4, or GIF format
Example value: STL.
         * @type {string || null}
         */
        this.Format = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.File3D = 'File3D' in params ? params.File3D : null;
        this.Format = 'Format' in params ? params.Format : null;

    }
}

/**
 * Submit3DSmartTopologyJob request structure.
 * @class
 */
class Submit3DSmartTopologyJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
         * @type {InputFile3D || null}
         */
        this.File3D = null;

        /**
         * Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
         * @type {string || null}
         */
        this.PolygonType = null;

        /**
         * Reduction level bit type
valid values: high, medium, low
         * @type {string || null}
         */
        this.FaceLevel = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.File3D) {
            let obj = new InputFile3D();
            obj.deserialize(params.File3D)
            this.File3D = obj;
        }
        this.PolygonType = 'PolygonType' in params ? params.PolygonType : null;
        this.FaceLevel = 'FaceLevel' in params ? params.FaceLevel : null;

    }
}

/**
 * Multi-Perspective images.
 * @class
 */
class ViewImage extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the viewing angle type.
Valid values: back, left, right.
         * @type {string || null}
         */
        this.ViewType = null;

        /**
         * Image Url.
         * @type {string || null}
         */
        this.ViewImageUrl = null;

        /**
         * base64 address of the image.
         * @type {string || null}
         */
        this.ViewImageBase64 = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ViewType = 'ViewType' in params ? params.ViewType : null;
        this.ViewImageUrl = 'ViewImageUrl' in params ? params.ViewImageUrl : null;
        this.ViewImageBase64 = 'ViewImageBase64' in params ? params.ViewImageBase64 : null;

    }
}

/**
 * QueryHunyuanTo3DProJob request structure.
 * @class
 */
class QueryHunyuanTo3DProJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID.
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

/**
 * QueryHunyuan3DPartJob response structure.
 * @class
 */
class QueryHunyuan3DPartJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status:
WAIT: waiting
RUN: running
FAIL: failed
DONE: successful
Example value: RUN
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * Generates the file URL with a valid period of 1 day
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * QueryHunyuanTo3DRapidJob response structure.
 * @class
 */
class QueryHunyuanTo3DRapidJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status:
WAIT: waiting
RUN: running
FAIL: failed
DONE: successful	
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message	
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * Specifies the generated 3D file array
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Translate the reply returned by the translation api, support multiple.
 * @class
 */
class TranslationChoice extends  AbstractModel {
    constructor(){
        super();

        /**
         * End flag, can be stop or sensitive.
stop means output ends normally.
sensitive only appears when streaming output review is enabled, indicating security review not passed.
         * @type {string || null}
         */
        this.FinishReason = null;

        /**
         * Index value, used when streaming.
         * @type {number || null}
         */
        this.Index = null;

        /**
         * Incremental return value used when streaming this field.
         * @type {TranslationDelta || null}
         */
        this.Delta = null;

        /**
         * Return value, used when non-streaming.
         * @type {TranslationMessage || null}
         */
        this.Message = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.FinishReason = 'FinishReason' in params ? params.FinishReason : null;
        this.Index = 'Index' in params ? params.Index : null;

        if (params.Delta) {
            let obj = new TranslationDelta();
            obj.deserialize(params.Delta)
            this.Delta = obj;
        }

        if (params.Message) {
            let obj = new TranslationMessage();
            obj.deserialize(params.Message)
            this.Message = obj;
        }

    }
}

/**
 * ChatTranslations response structure.
 * @class
 */
class ChatTranslationsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Request'S RequestId this time.
         * @type {string || null}
         */
        this.Id = null;

        /**
         * Disclaimer.
         * @type {string || null}
         */
        this.Note = null;

        /**
         * Unix timestamp, in seconds.
         * @type {number || null}
         */
        this.Created = null;

        /**
         * Token statistical information.
Billing by Token quantity.
         * @type {Usage || null}
         */
        this.Usage = null;

        /**
         * Reply content.
         * @type {Array.<TranslationChoice> || null}
         */
        this.Choices = null;

        /**
         * Error message.
If the service encounters an exception during streaming return, return this error.
         * @type {ErrorMsg || null}
         */
        this.ErrorMsg = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Id = 'Id' in params ? params.Id : null;
        this.Note = 'Note' in params ? params.Note : null;
        this.Created = 'Created' in params ? params.Created : null;

        if (params.Usage) {
            let obj = new Usage();
            obj.deserialize(params.Usage)
            this.Usage = obj;
        }

        if (params.Choices) {
            this.Choices = new Array();
            for (let z in params.Choices) {
                let obj = new TranslationChoice();
                obj.deserialize(params.Choices[z]);
                this.Choices.push(obj);
            }
        }

        if (params.ErrorMsg) {
            let obj = new ErrorMsg();
            obj.deserialize(params.ErrorMsg)
            this.ErrorMsg = obj;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SubmitHunyuanTo3DTextureEditJob request structure.
 * @class
 */
class SubmitHunyuanTo3DTextureEditJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * File URL of the 3D model file that requires texture edit
Supported formats: FBX
3D model limit: less than 100000 faces
         * @type {InputFile3D || null}
         */
        this.File3D = null;

        /**
         * Reference image for 3D model texture editing: Base64 data and image Url
Either Base64 or Url must be provided. if both are provided, Url prevails
Image restrictions: unilateral resolution less than 4096 and greater than 128, converted into Base64 string less than 10MB
Format support: jpg, jpeg, png
         * @type {ImageInfo || null}
         */
        this.Image = null;

        /**
         * Describes texture editing, forward prompt content
Supports up to 1024 utf-8 characters
Either image or prompt is required, and prompt and image cannot coexist
Example value: a kitten
         * @type {string || null}
         */
        this.Prompt = null;

        /**
         * Whether to enable the PBR texture parameter, only supports enabling when entering the Prompt
Example value: true
         * @type {boolean || null}
         */
        this.EnablePBR = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.File3D) {
            let obj = new InputFile3D();
            obj.deserialize(params.File3D)
            this.File3D = obj;
        }

        if (params.Image) {
            let obj = new ImageInfo();
            obj.deserialize(params.Image)
            this.Image = obj;
        }
        this.Prompt = 'Prompt' in params ? params.Prompt : null;
        this.EnablePBR = 'EnablePBR' in params ? params.EnablePBR : null;

    }
}

/**
 * Token quantity.
 * @class
 */
class Usage extends  AbstractModel {
    constructor(){
        super();

        /**
         * Input Token quantity.
         * @type {number || null}
         */
        this.PromptTokens = null;

        /**
         * Output Token quantity.
         * @type {number || null}
         */
        this.CompletionTokens = null;

        /**
         * Total Token quantity.
         * @type {number || null}
         */
        this.TotalTokens = null;

        /**
         * Details of the input token.
         * @type {PromptTokensDetails || null}
         */
        this.PromptTokensDetails = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.PromptTokens = 'PromptTokens' in params ? params.PromptTokens : null;
        this.CompletionTokens = 'CompletionTokens' in params ? params.CompletionTokens : null;
        this.TotalTokens = 'TotalTokens' in params ? params.TotalTokens : null;

        if (params.PromptTokensDetails) {
            let obj = new PromptTokensDetails();
            obj.deserialize(params.PromptTokensDetails)
            this.PromptTokensDetails = obj;
        }

    }
}

/**
 * SubmitHunyuanTo3DRapidJob response structure.
 * @class
 */
class SubmitHunyuanTo3DRapidJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID (valid period: 24 hours)
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ChatTranslations request structure.
 * @class
 */
class ChatTranslationsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Model name. optional values include hunyuan-translation.
Please read the introduction in [the product overview](https://www.tencentcloud.com/document/product/1284/75277) for model descriptions.

Note:
Different models have different pricing. according to [the purchase guide](https://www.tencentcloud.com/document/product/1284/77186), call as needed.
         * @type {string || null}
         */
        this.Model = null;

        /**
         * Streaming call switch.
Note:.
1. it defaults to non-streaming (false) when no value is passed.
2. for streaming calls, the results are incrementally returned via the SSE protocol (the return value is taken from Choices[n].Delta, and incremental data must be concatenated to obtain the complete result).
3. for non-streaming calls:.
The calling method is the same as an ordinary HTTP request.
The API response is time-consuming. if needed, set it to true for reduced latency.
Only return the final result once (return value takes the value from Choices[n].Message).

Note:.
When making an SDK call, streaming and non-streaming calls require **different ways** to obtain the return value. refer to the comments or sample code in the SDK (in the examples/hunyuan/v20230901/ directory of each language SDK code repository).
         * @type {boolean || null}
         */
        this.Stream = null;

        /**
         * Text to be translated.
         * @type {string || null}
         */
        this.Text = null;

        /**
         * Source language.
Supported language list:. 
Simplified chinese: zh, traditional chinese: zh-TR, cantonese: yue, english: en, french: fr, portuguese: pt, spanish: es, japanese: ja, turkish: TR, russian: ru, arabic: ar, korean: ko, thai: th, italian: it, german: de, vietnamese: vi, malay: ms, indonesian: id.
The following languages are supported only by the hunyuan-translation model:.
Filipino: fil, hindi: hi, polish: pl, czech: cs, dutch: nl, khmer: km, burmese: my, persian: fa, gujarati: gu, urdu: ur, telugu: te, marathi: mr, hebrew: he, bengali: bn, tamil: ta, ukrainian: uk, tibetan: bo, kazakh: kk, mongolian: mn, uyghur: ug.
         * @type {string || null}
         */
        this.Source = null;

        /**
         * Target language.
Supported language list:. 
Simplified chinese: zh, traditional chinese: zh-TR, cantonese: yue, english: en, french: fr, portuguese: pt, spanish: es, japanese: ja, turkish: TR, russian: ru, arabic: ar, korean: ko, thai: th, italian: it, german: de, vietnamese: vi, malay: ms, indonesian: id.
The following languages are supported only by the hunyuan-translation model:.
Filipino: fil, hindi: hi, polish: pl, czech: cs, dutch: nl, khmer: km, burmese: my, persian: fa, gujarati: gu, urdu: ur, telugu: te, marathi: mr, hebrew: he, bengali: bn, tamil: ta, ukrainian: uk, tibetan: bo, kazakh: kk, mongolian: mn, uyghur: ug.
         * @type {string || null}
         */
        this.Target = null;

        /**
         * Domain of the text to be translated, such as game plot.
         * @type {string || null}
         */
        this.Field = null;

        /**
         * Reference example, up to 10.
         * @type {Array.<Reference> || null}
         */
        this.References = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Model = 'Model' in params ? params.Model : null;
        this.Stream = 'Stream' in params ? params.Stream : null;
        this.Text = 'Text' in params ? params.Text : null;
        this.Source = 'Source' in params ? params.Source : null;
        this.Target = 'Target' in params ? params.Target : null;
        this.Field = 'Field' in params ? params.Field : null;

        if (params.References) {
            this.References = new Array();
            for (let z in params.References) {
                let obj = new Reference();
                obj.deserialize(params.References[z]);
                this.References.push(obj);
            }
        }

    }
}

/**
 * Specifies the detailed information of the input token.
 * @class
 */
class PromptTokensDetails extends  AbstractModel {
    constructor(){
        super();

        /**
         * The number of cache tokens.
         * @type {string || null}
         */
        this.CachedTokens = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.CachedTokens = 'CachedTokens' in params ? params.CachedTokens : null;

    }
}

/**
 * SubmitHunyuanTo3DUVJob request structure.
 * @class
 */
class SubmitHunyuanTo3DUVJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * File URL of the 3D model requiring UV unfold
Supported formats: FBX, OBJ, GLB
3D model limit: less than 30000 faces
         * @type {InputFile3D || null}
         */
        this.File = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.File) {
            let obj = new InputFile3D();
            obj.deserialize(params.File)
            this.File = obj;
        }

    }
}

/**
 * Submit3DSmartTopologyJob response structure.
 * @class
 */
class Submit3DSmartTopologyJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID.	
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SubmitHunyuanTo3DTextureEditJob response structure.
 * @class
 */
class SubmitHunyuanTo3DTextureEditJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task id (valid period 24 hours)
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * 3D model related files, files or textures.
 * @class
 */
class File3D extends  AbstractModel {
    constructor(){
        super();

        /**
         * 3D model or texture. valid values: GIF or OBJ or Image.
         * @type {string || null}
         */
        this.Type = null;

        /**
         * Specifies the file Url (valid for 24 hours).
         * @type {string || null}
         */
        this.Url = null;

        /**
         * Preview image Url.
         * @type {string || null}
         */
        this.PreviewImageUrl = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Type = 'Type' in params ? params.Type : null;
        this.Url = 'Url' in params ? params.Url : null;
        this.PreviewImageUrl = 'PreviewImageUrl' in params ? params.PreviewImageUrl : null;

    }
}

/**
 * QueryHunyuanTo3DTextureEditJob response structure.
 * @class
 */
class QueryHunyuanTo3DTextureEditJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status
WAIT: waiting; 
RUN: running; 
FAIL: failed; 
DONE: successful;
Example value: RUN	
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * The URL address for generating texture files is valid for 1 day.
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * 3D file.
 * @class
 */
class InputFile3D extends  AbstractModel {
    constructor(){
        super();

        /**
         * Specifies the file Url with a valid period of 24 hours.	
         * @type {string || null}
         */
        this.Url = null;

        /**
         * Specifies the file format.	
         * @type {string || null}
         */
        this.Type = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Url = 'Url' in params ? params.Url : null;
        this.Type = 'Type' in params ? params.Type : null;

    }
}

/**
 * Translate the API response content (streaming return).
 * @class
 */
class TranslationDelta extends  AbstractModel {
    constructor(){
        super();

        /**
         * Role name.
         * @type {string || null}
         */
        this.Role = null;

        /**
         * Content details.
         * @type {string || null}
         */
        this.Content = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Role = 'Role' in params ? params.Role : null;
        this.Content = 'Content' in params ? params.Content : null;

    }
}

/**
 * SubmitHunyuanTo3DRapidJob request structure.
 * @class
 */
class SubmitHunyuanTo3DRapidJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Text-To-3D, description of 3D content, forward Prompt content
Supports up to 200 utf-8 characters
Either ImageBase64, ImageUrl, or Prompt is required, and Prompt cannot coexist with ImageBase64/ImageUrl
         * @type {string || null}
         */
        this.Prompt = null;

        /**
         * Input image Base64 data
Size: unilateral resolution requirement not less than 128, not greater than 5000, size not greater than 6mb (after encoding, size increases by approximately 30%). format:
jpg, png, jpeg, webp
Imagebase64, imageurl, and Prompt are required, but Prompt and imagebase64/imageurl cannot coexist
         * @type {string || null}
         */
        this.ImageBase64 = null;

        /**
         * Input image Url size: 
Unilateral resolution requirement not less than 128, not greater than 5000. size not greater than 8mb
Format: jpg, png, jpeg, webp
Imagebase64, imageurl, and Prompt are required, and Prompt cannot coexist with imagebase64/imageurl	
         * @type {string || null}
         */
        this.ImageUrl = null;

        /**
         * Returns the 3D file format. valid values:
OBJ, GLB, STL, USDZ, FBX, MP4, GIF
Recommended input models below 50W, may timeout when selecting USDZ, MP4, or GIF format
Example value: STL
         * @type {string || null}
         */
        this.ResultFormat = null;

        /**
         * Specifies whether PBR material generation is enabled, false by default.	
         * @type {boolean || null}
         */
        this.EnablePBR = null;

        /**
         * Specifies whether to enable the single geometry generation option
When enabled, it generates a 3D model without textures (white model)
When enabled, the generative model does not support OBJ format
Default model file format is GLB
         * @type {boolean || null}
         */
        this.EnableGeometry = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Prompt = 'Prompt' in params ? params.Prompt : null;
        this.ImageBase64 = 'ImageBase64' in params ? params.ImageBase64 : null;
        this.ImageUrl = 'ImageUrl' in params ? params.ImageUrl : null;
        this.ResultFormat = 'ResultFormat' in params ? params.ResultFormat : null;
        this.EnablePBR = 'EnablePBR' in params ? params.EnablePBR : null;
        this.EnableGeometry = 'EnableGeometry' in params ? params.EnableGeometry : null;

    }
}

/**
 * SubmitHunyuanTo3DUVJob response structure.
 * @class
 */
class SubmitHunyuanTo3DUVJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID.	
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SubmitHunyuan3DPartJob response structure.
 * @class
 */
class SubmitHunyuan3DPartJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task id (valid period: 24 hours)
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * SubmitHunyuanTo3DProJob request structure.
 * @class
 */
class SubmitHunyuanTo3DProJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Tencent HY 3D Global model version
Defaults to 3.0, with optional choices: 3.0, 3.1
When selecting version 3.1, the [LowPoly] and [Sketch] parameter is unavailable
Example value:3.0
         * @type {string || null}
         */
        this.Model = null;

        /**
         * Generates 3D content, describes 3D content.
Supports up to 1024 utf-8 characters.
Text-To-3D. Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
         * @type {string || null}
         */
        this.Prompt = null;

        /**
         * Enter the Base64 code of the image.
Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
Input image suggestion:
1.Simple background (solid-color background) 
2.No text or blended colors
3.Single object
4.The object occupies over 50% of the frame
Valid values: jpg, png, jpeg, webp.
Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
         * @type {string || null}
         */
        this.ImageBase64 = null;

        /**
         * Input image Url.
Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
Input image suggestion:
1.Simple background (solid-color background) 
2.No text or blended colors
3.Single object
4.The object occupies over 50% of the frame
Valid values: jpg, png, jpeg, webp.
Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
         * @type {string || null}
         */
        this.ImageUrl = null;

        /**
         * Multi-Perspective model image. reference value for viewing angle:.
left: Left view;
right: Right view;
back: Rear view;
top: Top view (only supported in Model 3.1);
bottom: Bottom view (only supported in Model 3.1);
left_front: Left front 45 degree view (only supported in Model 3.1);
right_front: Right front 45 degree view (only supported in Model 3.1);

Each perspective is limited to one image.
Image size limit. the value must not exceed 8 mb after encoding.
Image resolution limitation: the unilateral resolution should be less than 5000 and greater than 128.
Supported image format: JPG or PNG
         * @type {Array.<ViewImage> || null}
         */
        this.MultiViewImages = null;

        /**
         * Specifies whether PBR material generation is enabled. default false
         * @type {boolean || null}
         */
        this.EnablePBR = null;

        /**
         * Specifies the face count for 3D model generation. default value is 500000.
Specifies the supported face count generation range. value range: 40000-1500000
         * @type {number || null}
         */
        this.FaceCount = null;

        /**
         * Generation task type. default: Normal. valid values:
Normal: generates a geometric model with textures
LowPoly: specifies the model generated after intelligent polygon reduction.
Geometry: specifies whether to generate a Geometry model without textures (white model). when this task is selected, the EnablePBR parameter does not take effect
Specifies the Sketch for the generative model, allowing input of a Sketch or line drawing. in this mode, both prompt and ImageUrl/ImageBase64 can be entered together
         * @type {string || null}
         */
        this.GenerateType = null;

        /**
         * This parameter only takes effect when LowPoly mode is selected from GenerateType

Polygon type, indicates the number of sides in the model's surface grid, defaults to triangle. valid values:
triangle. specifies the triangular face
quadrilateral: mix quadrangle and triangle faces to generate
         * @type {string || null}
         */
        this.PolygonType = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Model = 'Model' in params ? params.Model : null;
        this.Prompt = 'Prompt' in params ? params.Prompt : null;
        this.ImageBase64 = 'ImageBase64' in params ? params.ImageBase64 : null;
        this.ImageUrl = 'ImageUrl' in params ? params.ImageUrl : null;

        if (params.MultiViewImages) {
            this.MultiViewImages = new Array();
            for (let z in params.MultiViewImages) {
                let obj = new ViewImage();
                obj.deserialize(params.MultiViewImages[z]);
                this.MultiViewImages.push(obj);
            }
        }
        this.EnablePBR = 'EnablePBR' in params ? params.EnablePBR : null;
        this.FaceCount = 'FaceCount' in params ? params.FaceCount : null;
        this.GenerateType = 'GenerateType' in params ? params.GenerateType : null;
        this.PolygonType = 'PolygonType' in params ? params.PolygonType : null;

    }
}

/**
 * QueryHunyuanTo3DTextureEditJob request structure.
 * @class
 */
class QueryHunyuanTo3DTextureEditJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

/**
 * Convert3DFormat response structure.
 * @class
 */
class Convert3DFormatResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * 3D file address
         * @type {string || null}
         */
        this.ResultFile3D = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ResultFile3D = 'ResultFile3D' in params ? params.ResultFile3D : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeHunyuanTo3DUVJob request structure.
 * @class
 */
class DescribeHunyuanTo3DUVJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

/**
 * SubmitHunyuan3DPartJob request structure.
 * @class
 */
class SubmitHunyuan3DPartJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
         * @type {InputFile3D || null}
         */
        this.File = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.File) {
            let obj = new InputFile3D();
            obj.deserialize(params.File)
            this.File = obj;
        }

    }
}

/**
 * Describe3DSmartTopologyJob response structure.
 * @class
 */
class Describe3DSmartTopologyJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status. WAIT: waiting; RUN: running; FAIL: failed; DONE: successful. example value: RUN.	
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code.	
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message.	
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * File generation URL address, with a valid period of 1 day.	
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeHunyuanTo3DUVJob response structure.
 * @class
 */
class DescribeHunyuanTo3DUVJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status
WAIT: waiting;
RUN: running; 
FAIL: failed; 
DONE: successful;
Example value: RUN
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * File generation URL address, with a valid period of 1 day
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Translate dialogue reference example.
 * @class
 */
class Reference extends  AbstractModel {
    constructor(){
        super();

        /**
         * Translate text type, enumerate "sentence" means sentence, "term" means terminology.
         * @type {string || null}
         */
        this.Type = null;

        /**
         * Original.
         * @type {string || null}
         */
        this.Text = null;

        /**
         * Translation.
         * @type {string || null}
         */
        this.Translation = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Type = 'Type' in params ? params.Type : null;
        this.Text = 'Text' in params ? params.Text : null;
        this.Translation = 'Translation' in params ? params.Translation : null;

    }
}

/**
 * Image information.
 * @class
 */
class ImageInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Image Url.
         * @type {string || null}
         */
        this.Url = null;

        /**
         * Image Base64.
         * @type {string || null}
         */
        this.Base64 = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Url = 'Url' in params ? params.Url : null;
        this.Base64 = 'Base64' in params ? params.Base64 : null;

    }
}

/**
 * SubmitHunyuanTo3DProJob response structure.
 * @class
 */
class SubmitHunyuanTo3DProJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID (valid period: 24 hours).
         * @type {string || null}
         */
        this.JobId = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Runtime exception message.
 * @class
 */
class ErrorMsg extends  AbstractModel {
    constructor(){
        super();

        /**
         * Error message.
         * @type {string || null}
         */
        this.Msg = null;

        /**
         * Error code.
4000 internal service error.
4001 request model timeout.

         * @type {number || null}
         */
        this.Code = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Msg = 'Msg' in params ? params.Msg : null;
        this.Code = 'Code' in params ? params.Code : null;

    }
}

/**
 * QueryHunyuanTo3DProJob response structure.
 * @class
 */
class QueryHunyuanTo3DProJobResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task status:
WAIT: waiting
RUN: running; FAIL: failed
DONE: successful
         * @type {string || null}
         */
        this.Status = null;

        /**
         * Error code
         * @type {string || null}
         */
        this.ErrorCode = null;

        /**
         * Error message
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * Describes the generated 3d file array
         * @type {Array.<File3D> || null}
         */
        this.ResultFile3Ds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Status = 'Status' in params ? params.Status : null;
        this.ErrorCode = 'ErrorCode' in params ? params.ErrorCode : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;

        if (params.ResultFile3Ds) {
            this.ResultFile3Ds = new Array();
            for (let z in params.ResultFile3Ds) {
                let obj = new File3D();
                obj.deserialize(params.ResultFile3Ds[z]);
                this.ResultFile3Ds.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * QueryHunyuan3DPartJob request structure.
 * @class
 */
class QueryHunyuan3DPartJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

/**
 * Translate the session content via translation api.
 * @class
 */
class TranslationMessage extends  AbstractModel {
    constructor(){
        super();

        /**
         * Role. valid values: system, user, assistant, tool.
         * @type {string || null}
         */
        this.Role = null;

        /**
         * Text content.
         * @type {string || null}
         */
        this.Content = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Role = 'Role' in params ? params.Role : null;
        this.Content = 'Content' in params ? params.Content : null;

    }
}

/**
 * QueryHunyuanTo3DRapidJob request structure.
 * @class
 */
class QueryHunyuanTo3DRapidJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID.	
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

/**
 * Describe3DSmartTopologyJob request structure.
 * @class
 */
class Describe3DSmartTopologyJobRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task ID.	
         * @type {string || null}
         */
        this.JobId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.JobId = 'JobId' in params ? params.JobId : null;

    }
}

module.exports = {
    Convert3DFormatRequest: Convert3DFormatRequest,
    Submit3DSmartTopologyJobRequest: Submit3DSmartTopologyJobRequest,
    ViewImage: ViewImage,
    QueryHunyuanTo3DProJobRequest: QueryHunyuanTo3DProJobRequest,
    QueryHunyuan3DPartJobResponse: QueryHunyuan3DPartJobResponse,
    QueryHunyuanTo3DRapidJobResponse: QueryHunyuanTo3DRapidJobResponse,
    TranslationChoice: TranslationChoice,
    ChatTranslationsResponse: ChatTranslationsResponse,
    SubmitHunyuanTo3DTextureEditJobRequest: SubmitHunyuanTo3DTextureEditJobRequest,
    Usage: Usage,
    SubmitHunyuanTo3DRapidJobResponse: SubmitHunyuanTo3DRapidJobResponse,
    ChatTranslationsRequest: ChatTranslationsRequest,
    PromptTokensDetails: PromptTokensDetails,
    SubmitHunyuanTo3DUVJobRequest: SubmitHunyuanTo3DUVJobRequest,
    Submit3DSmartTopologyJobResponse: Submit3DSmartTopologyJobResponse,
    SubmitHunyuanTo3DTextureEditJobResponse: SubmitHunyuanTo3DTextureEditJobResponse,
    File3D: File3D,
    QueryHunyuanTo3DTextureEditJobResponse: QueryHunyuanTo3DTextureEditJobResponse,
    InputFile3D: InputFile3D,
    TranslationDelta: TranslationDelta,
    SubmitHunyuanTo3DRapidJobRequest: SubmitHunyuanTo3DRapidJobRequest,
    SubmitHunyuanTo3DUVJobResponse: SubmitHunyuanTo3DUVJobResponse,
    SubmitHunyuan3DPartJobResponse: SubmitHunyuan3DPartJobResponse,
    SubmitHunyuanTo3DProJobRequest: SubmitHunyuanTo3DProJobRequest,
    QueryHunyuanTo3DTextureEditJobRequest: QueryHunyuanTo3DTextureEditJobRequest,
    Convert3DFormatResponse: Convert3DFormatResponse,
    DescribeHunyuanTo3DUVJobRequest: DescribeHunyuanTo3DUVJobRequest,
    SubmitHunyuan3DPartJobRequest: SubmitHunyuan3DPartJobRequest,
    Describe3DSmartTopologyJobResponse: Describe3DSmartTopologyJobResponse,
    DescribeHunyuanTo3DUVJobResponse: DescribeHunyuanTo3DUVJobResponse,
    Reference: Reference,
    ImageInfo: ImageInfo,
    SubmitHunyuanTo3DProJobResponse: SubmitHunyuanTo3DProJobResponse,
    ErrorMsg: ErrorMsg,
    QueryHunyuanTo3DProJobResponse: QueryHunyuanTo3DProJobResponse,
    QueryHunyuan3DPartJobRequest: QueryHunyuan3DPartJobRequest,
    TranslationMessage: TranslationMessage,
    QueryHunyuanTo3DRapidJobRequest: QueryHunyuanTo3DRapidJobRequest,
    Describe3DSmartTopologyJobRequest: Describe3DSmartTopologyJobRequest,

}
