/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * Recoverable time interval
 * @class
 */
class ArchiveLogInterval extends  AbstractModel {
    constructor(){
        super();

        /**
         * End time.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.EndTime = null;

        /**
         * Major version.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.MajorVersion = null;

        /**
         * Minor version.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.MinorVersion = null;

        /**
         * Start time.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.StartTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.EndTime = 'EndTime' in params ? params.EndTime : null;
        this.MajorVersion = 'MajorVersion' in params ? params.MajorVersion : null;
        this.MinorVersion = 'MinorVersion' in params ? params.MinorVersion : null;
        this.StartTime = 'StartTime' in params ? params.StartTime : null;

    }
}

/**
 * IsolateDBInstance request structure.
 * @class
 */
class IsolateDBInstanceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of isolated instance ids required.
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;

    }
}

/**
 * DescribeFlow request structure.
 * @class
 */
class DescribeFlowRequest extends  AbstractModel {
    constructor(){
        super();

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

    }
}

/**
 * ModifyDBSBackupSetComment response structure.
 * @class
 */
class ModifyDBSBackupSetCommentResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>Whether it is successful</p>.
         * @type {boolean || null}
         */
        this.IsSuccess = null;

        /**
         * <P>Modify information</p>.
         * @type {string || null}
         */
        this.Msg = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.IsSuccess = 'IsSuccess' in params ? params.IsSuccess : null;
        this.Msg = 'Msg' in params ? params.Msg : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyInstanceName response structure.
 * @class
 */
class ModifyInstanceNameResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyDBInstanceSecurityGroups response structure.
 * @class
 */
class ModifyDBInstanceSecurityGroupsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeDBParameters request structure.
 * @class
 */
class DescribeDBParametersRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID, for example: tdsql3-ow728lmc.
         * @type {string || null}
         */
        this.InstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;

    }
}

/**
 * DescribeDatabaseObjects response structure.
 * @class
 */
class DescribeDatabaseObjectsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Passthrough input parameter.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Database name.
         * @type {string || null}
         */
        this.DbName = null;

        /**
         * Table list.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<DatabaseTable> || null}
         */
        this.Tables = null;

        /**
         * View list.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<DatabaseView> || null}
         */
        this.Views = null;

        /**
         * Stored procedure list.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<DatabaseProcedure> || null}
         */
        this.Procs = null;

        /**
         * Function list.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<DatabaseFunction> || null}
         */
        this.Funcs = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.DbName = 'DbName' in params ? params.DbName : null;

        if (params.Tables) {
            this.Tables = new Array();
            for (let z in params.Tables) {
                let obj = new DatabaseTable();
                obj.deserialize(params.Tables[z]);
                this.Tables.push(obj);
            }
        }

        if (params.Views) {
            this.Views = new Array();
            for (let z in params.Views) {
                let obj = new DatabaseView();
                obj.deserialize(params.Views[z]);
                this.Views.push(obj);
            }
        }

        if (params.Procs) {
            this.Procs = new Array();
            for (let z in params.Procs) {
                let obj = new DatabaseProcedure();
                obj.deserialize(params.Procs[z]);
                this.Procs.push(obj);
            }
        }

        if (params.Funcs) {
            this.Funcs = new Array();
            for (let z in params.Funcs) {
                let obj = new DatabaseFunction();
                obj.deserialize(params.Funcs[z]);
                this.Funcs.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Inbound and outbound rules.
 * @class
 */
class SecurityGroupBound extends  AbstractModel {
    constructor(){
        super();

        /**
         * Source IP or IP range, such as 192.168.0.0/16.
         * @type {string || null}
         */
        this.CidrIp = null;

        /**
         * Policy, ACCEPT or DROP.
         * @type {string || null}
         */
        this.Action = null;

        /**
         * Port.
         * @type {string || null}
         */
        this.PortRange = null;

        /**
         * Network protocol, supports UDP, TCP.
         * @type {string || null}
         */
        this.IpProtocol = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.CidrIp = 'CidrIp' in params ? params.CidrIp : null;
        this.Action = 'Action' in params ? params.Action : null;
        this.PortRange = 'PortRange' in params ? params.PortRange : null;
        this.IpProtocol = 'IpProtocol' in params ? params.IpProtocol : null;

    }
}

/**
 * CreateDBSBackup response structure.
 * @class
 */
class CreateDBSBackupResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Backup set ID.</p>.
         * @type {number || null}
         */
        this.BackupSetId = null;

        /**
         * <P>Whether it is successful</p>.
         * @type {boolean || null}
         */
        this.IsSuccess = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.BackupSetId = 'BackupSetId' in params ? params.BackupSetId : null;
        this.IsSuccess = 'IsSuccess' in params ? params.IsSuccess : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreateDBSBackup request structure.
 * @class
 */
class CreateDBSBackupRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Backup method: physical, snapshot. this value should be consistent with the backupMethod in the api response of DescribeDBSBackupPolicy.</p>enumeration value:<ul><li> physical: physical backup</li><li> snapshot: snapshot backup</li></ul>
         * @type {string || null}
         */
        this.BackupMethod = null;

        /**
         * <P>Backup type: currently, only supports full.</p>
         * @type {string || null}
         */
        this.BackupType = null;

        /**
         * <p>Instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <P>Backup notes.</p>
         * @type {string || null}
         */
        this.BackupName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.BackupMethod = 'BackupMethod' in params ? params.BackupMethod : null;
        this.BackupType = 'BackupType' in params ? params.BackupType : null;
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.BackupName = 'BackupName' in params ? params.BackupName : null;

    }
}

/**
 * DestroyInstances request structure.
 * @class
 */
class DestroyInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of isolated instance ids required.
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;

    }
}

/**
 * DescribeDBSecurityGroups request structure.
 * @class
 */
class DescribeDBSecurityGroupsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;

    }
}

/**
 * ModifyDBParameters response structure.
 * @class
 */
class ModifyDBParametersResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Task id.
         * @type {number || null}
         */
        this.TaskID = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.TaskID = 'TaskID' in params ? params.TaskID : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyInstanceName request structure.
 * @class
 */
class ModifyInstanceNameRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance id that needs to be modified.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Modified instance name. required length: 1-60. can contain chinese, english uppercase and lowercase letters, digits, -, _.
         * @type {string || null}
         */
        this.InstanceName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.InstanceName = 'InstanceName' in params ? params.InstanceName : null;

    }
}

/**
 * DB parameter description.
 * @class
 */
class ParamDesc extends  AbstractModel {
    constructor(){
        super();

        /**
         * Parameter name.
         * @type {string || null}
         */
        this.Param = null;

        /**
         * Current parameter value.
         * @type {string || null}
         */
        this.Value = null;

        /**
         * The configured value is the same as the value once the parameter takes effect.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.SetValue = null;

        /**
         * System default value.
         * @type {string || null}
         */
        this.Default = null;

        /**
         * Parameter limits.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {ParamConstraint || null}
         */
        this.Constraint = null;

        /**
         * Whether a value has been set. false: not set. true: has set.
         * @type {boolean || null}
         */
        this.HaveSetValue = null;

        /**
         * true: restart required.
         * @type {boolean || null}
         */
        this.NeedRestart = null;

        /**
         * Parameter description.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Description = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Param = 'Param' in params ? params.Param : null;
        this.Value = 'Value' in params ? params.Value : null;
        this.SetValue = 'SetValue' in params ? params.SetValue : null;
        this.Default = 'Default' in params ? params.Default : null;

        if (params.Constraint) {
            let obj = new ParamConstraint();
            obj.deserialize(params.Constraint)
            this.Constraint = obj;
        }
        this.HaveSetValue = 'HaveSetValue' in params ? params.HaveSetValue : null;
        this.NeedRestart = 'NeedRestart' in params ? params.NeedRestart : null;
        this.Description = 'Description' in params ? params.Description : null;

    }
}

/**
 * ModifyAutoRenewFlag request structure.
 * @class
 */
class ModifyAutoRenewFlagRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>Instance list that needs to be modified</p>.
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

        /**
         * <P>1 enables automatic renewal, 0 disables automatic renewal.</p>.
         * @type {number || null}
         */
        this.AutoRenewFlag = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;
        this.AutoRenewFlag = 'AutoRenewFlag' in params ? params.AutoRenewFlag : null;

    }
}

/**
 * ModifyDBSBackupPolicy response structure.
 * @class
 */
class ModifyDBSBackupPolicyResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Success status.
         * @type {boolean || null}
         */
        this.IsSuccess = null;

        /**
         * Message.
         * @type {string || null}
         */
        this.Msg = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.IsSuccess = 'IsSuccess' in params ? params.IsSuccess : null;
        this.Msg = 'Msg' in params ? params.Msg : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeDBSCloneInstances response structure.
 * @class
 */
class DescribeDBSCloneInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>Clone list</p>.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<CloneInstanceModel> || null}
         */
        this.Items = null;

        /**
         * <p>Total</p>
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Items) {
            this.Items = new Array();
            for (let z in params.Items) {
                let obj = new CloneInstanceModel();
                obj.deserialize(params.Items[z]);
                this.Items.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeDBSecurityGroups response structure.
 * @class
 */
class DescribeDBSecurityGroupsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Security group description.
         * @type {Array.<SecurityGroup> || null}
         */
        this.Groups = null;

        /**
         * Instance VIP.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.VIP = null;

        /**
         * Instance port.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.VPort = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Groups) {
            this.Groups = new Array();
            for (let z in params.Groups) {
                let obj = new SecurityGroup();
                obj.deserialize(params.Groups[z]);
                this.Groups.push(obj);
            }
        }
        this.VIP = 'VIP' in params ? params.VIP : null;
        this.VPort = 'VPort' in params ? params.VPort : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Modify backup policy object.
 * @class
 */
class BackupPolicyModelInput extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>Backup end time.</p>
         * @type {string || null}
         */
        this.BackupEndTime = null;

        /**
         * <P>Backup method: physical physical backup, snapshot snapshot backup</p>
         * @type {string || null}
         */
        this.BackupMethod = null;

        /**
         * <P>Backup start time</p>
         * @type {string || null}
         */
        this.BackupStartTime = null;

        /**
         * <P>Whether full backup is enabled</p>
         * @type {number || null}
         */
        this.EnableFull = null;

        /**
         * <P>Whether to enable log backup</p>
         * @type {number || null}
         */
        this.EnableLog = null;

        /**
         * <P>Full backup retention time can currently only be set to 7 days.</p>
         * @type {number || null}
         */
        this.FullRetentionPeriod = null;

        /**
         * <p>Instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <P>Log retention days. currently, can only set retention to 7 days.</p>
         * @type {number || null}
         */
        this.LogRetentionPeriod = null;

        /**
         * <P>Days of the week to perform backup.</p>
         * @type {string || null}
         */
        this.PeriodTime = null;

        /**
         * <p>Storage type: COS, SNAPSHOT</p>valid values: <ul><li> COS: COS storage</li><li> SNAPSHOT: cloud disk SNAPSHOT</li></ul>
         * @type {string || null}
         */
        this.StorageType = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.BackupEndTime = 'BackupEndTime' in params ? params.BackupEndTime : null;
        this.BackupMethod = 'BackupMethod' in params ? params.BackupMethod : null;
        this.BackupStartTime = 'BackupStartTime' in params ? params.BackupStartTime : null;
        this.EnableFull = 'EnableFull' in params ? params.EnableFull : null;
        this.EnableLog = 'EnableLog' in params ? params.EnableLog : null;
        this.FullRetentionPeriod = 'FullRetentionPeriod' in params ? params.FullRetentionPeriod : null;
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.LogRetentionPeriod = 'LogRetentionPeriod' in params ? params.LogRetentionPeriod : null;
        this.PeriodTime = 'PeriodTime' in params ? params.PeriodTime : null;
        this.StorageType = 'StorageType' in params ? params.StorageType : null;

    }
}

/**
 * Database function information.
 * @class
 */
class DatabaseFunction extends  AbstractModel {
    constructor(){
        super();

        /**
         * Function name.
         * @type {string || null}
         */
        this.Func = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Func = 'Func' in params ? params.Func : null;

    }
}

/**
 * ModifyDBSBackupPolicy request structure.
 * @class
 */
class ModifyDBSBackupPolicyRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Backup policy.
         * @type {BackupPolicyModelInput || null}
         */
        this.BackupPolicy = null;

        /**
         * Instance ID.
         * @type {string || null}
         */
        this.InstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.BackupPolicy) {
            let obj = new BackupPolicyModelInput();
            obj.deserialize(params.BackupPolicy)
            this.BackupPolicy = obj;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;

    }
}

/**
 * DescribeDBSCloneInstances request structure.
 * @class
 */
class DescribeDBSCloneInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Source instance ID.</p>
         * @type {string || null}
         */
        this.SourceInstanceId = null;

        /**
         * <P>Engine type</p>
         * @type {string || null}
         */
        this.DBType = null;

        /**
         * <P>Creation end time</p>
         * @type {string || null}
         */
        this.EndCreateTime = null;

        /**
         * <p>Clone kind: PITR time point BackupSet backup set</p>
         * @type {string || null}
         */
        this.FilterCloneType = null;

        /**
         * <P>Query count [0,200]</p>
         * @type {number || null}
         */
        this.Limit = null;

        /**
         * <p>Query offset [0,INF]</p>
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * <p>Sorting field: CloneTime, CreateTime</p>
         * @type {string || null}
         */
        this.OrderBy = null;

        /**
         * <p>Sorting type: ASC, DESC</p>
         * @type {string || null}
         */
        this.OrderType = null;

        /**
         * <P>Creation start time</p>
         * @type {string || null}
         */
        this.StartCreateTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SourceInstanceId = 'SourceInstanceId' in params ? params.SourceInstanceId : null;
        this.DBType = 'DBType' in params ? params.DBType : null;
        this.EndCreateTime = 'EndCreateTime' in params ? params.EndCreateTime : null;
        this.FilterCloneType = 'FilterCloneType' in params ? params.FilterCloneType : null;
        this.Limit = 'Limit' in params ? params.Limit : null;
        this.Offset = 'Offset' in params ? params.Offset : null;
        this.OrderBy = 'OrderBy' in params ? params.OrderBy : null;
        this.OrderType = 'OrderType' in params ? params.OrderType : null;
        this.StartCreateTime = 'StartCreateTime' in params ? params.StartCreateTime : null;

    }
}

/**
 * DescribeDatabaseObjects request structure.
 * @class
 */
class DescribeDatabaseObjectsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID, for example: tdsql3-42f40429.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Database name, obtained via the DescribeDatabases api.
         * @type {string || null}
         */
        this.DbName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.DbName = 'DbName' in params ? params.DbName : null;

    }
}

/**
 * DescribeDBSAvailableRecoveryTime response structure.
 * @class
 */
class DescribeDBSAvailableRecoveryTimeResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.EndTime = null;

        /**
         * <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {Array.<ArchiveLogInterval> || null}
         */
        this.Intervals = null;

        /**
         * <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.StartTime = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.EndTime = 'EndTime' in params ? params.EndTime : null;

        if (params.Intervals) {
            this.Intervals = new Array();
            for (let z in params.Intervals) {
                let obj = new ArchiveLogInterval();
                obj.deserialize(params.Intervals[z]);
                this.Intervals.push(obj);
            }
        }
        this.StartTime = 'StartTime' in params ? params.StartTime : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ModifyAutoRenewFlag response structure.
 * @class
 */
class ModifyAutoRenewFlagResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DestroyInstances response structure.
 * @class
 */
class DestroyInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of successfully isolated instance ids.
         * @type {Array.<string> || null}
         */
        this.SuccessInstanceIds = null;

        /**
         * Isolation removal failed instance Id list.
         * @type {Array.<string> || null}
         */
        this.FailedInstanceIds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SuccessInstanceIds = 'SuccessInstanceIds' in params ? params.SuccessInstanceIds : null;
        this.FailedInstanceIds = 'FailedInstanceIds' in params ? params.FailedInstanceIds : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeDBParameters response structure.
 * @class
 */
class DescribeDBParametersResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID, for example: tdsql3-ow728lmc.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Request the current parameter value of the instance.
         * @type {Array.<ParamDesc> || null}
         */
        this.Params = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;

        if (params.Params) {
            this.Params = new Array();
            for (let z in params.Params) {
                let obj = new ParamDesc();
                obj.deserialize(params.Params[z]);
                this.Params.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Security group details.
 * @class
 */
class SecurityGroup extends  AbstractModel {
    constructor(){
        super();

        /**
         * Project ID.
         * @type {number || null}
         */
        this.ProjectId = null;

        /**
         * CreationTime, time format: yyyy-mm-dd hh:mm:ss.
         * @type {string || null}
         */
        this.CreateTime = null;

        /**
         * Security group ID.
         * @type {string || null}
         */
        this.SecurityGroupId = null;

        /**
         * Security group name.
         * @type {string || null}
         */
        this.SecurityGroupName = null;

        /**
         * Security group remarks
         * @type {string || null}
         */
        this.SecurityGroupRemark = null;

        /**
         * Inbound rule.
         * @type {Array.<SecurityGroupBound> || null}
         */
        this.Inbound = null;

        /**
         * Outbound rule.
         * @type {Array.<SecurityGroupBound> || null}
         */
        this.Outbound = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ProjectId = 'ProjectId' in params ? params.ProjectId : null;
        this.CreateTime = 'CreateTime' in params ? params.CreateTime : null;
        this.SecurityGroupId = 'SecurityGroupId' in params ? params.SecurityGroupId : null;
        this.SecurityGroupName = 'SecurityGroupName' in params ? params.SecurityGroupName : null;
        this.SecurityGroupRemark = 'SecurityGroupRemark' in params ? params.SecurityGroupRemark : null;

        if (params.Inbound) {
            this.Inbound = new Array();
            for (let z in params.Inbound) {
                let obj = new SecurityGroupBound();
                obj.deserialize(params.Inbound[z]);
                this.Inbound.push(obj);
            }
        }

        if (params.Outbound) {
            this.Outbound = new Array();
            for (let z in params.Outbound) {
                let obj = new SecurityGroupBound();
                obj.deserialize(params.Outbound[z]);
                this.Outbound.push(obj);
            }
        }

    }
}

/**
 * IsolateDBInstance response structure.
 * @class
 */
class IsolateDBInstanceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Isolation successful instance Id list.
         * @type {Array.<string> || null}
         */
        this.SuccessInstanceIds = null;

        /**
         * Isolation failed instance Id list.
         * @type {Array.<string> || null}
         */
        this.FailedInstanceIds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SuccessInstanceIds = 'SuccessInstanceIds' in params ? params.SuccessInstanceIds : null;
        this.FailedInstanceIds = 'FailedInstanceIds' in params ? params.FailedInstanceIds : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeDBSAvailableRecoveryTime request structure.
 * @class
 */
class DescribeDBSAvailableRecoveryTimeRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>db instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <p>Backup set ID. the value comes from the DescribeDBSBackupSets api response.</p>
         * @type {number || null}
         */
        this.BackupSetId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.BackupSetId = 'BackupSetId' in params ? params.BackupSetId : null;

    }
}

/**
 * Database table information.
 * @class
 */
class DatabaseTable extends  AbstractModel {
    constructor(){
        super();

        /**
         * Table name
         * @type {string || null}
         */
        this.Table = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Table = 'Table' in params ? params.Table : null;

    }
}

/**
 * DeleteDBSBackupSets response structure.
 * @class
 */
class DeleteDBSBackupSetsResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * <P>Number of backups deleted this time.</p>
         * @type {number || null}
         */
        this.Deleted = null;

        /**
         * <P>Whether all are deleted successfully.</p>
         * @type {boolean || null}
         */
        this.IsSuccess = null;

        /**
         * <P>Total number of backups to be deleted.</p>
         * @type {number || null}
         */
        this.Total = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Deleted = 'Deleted' in params ? params.Deleted : null;
        this.IsSuccess = 'IsSuccess' in params ? params.IsSuccess : null;
        this.Total = 'Total' in params ? params.Total : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeFlow response structure.
 * @class
 */
class DescribeFlowResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Value range of the constraint type.
 * @class
 */
class ConstraintRange extends  AbstractModel {
    constructor(){
        super();

        /**
         * Minimum value when the constraint type is section.
         * @type {string || null}
         */
        this.Min = null;

        /**
         * Specifies the maximum value when the constraint type is section.
         * @type {string || null}
         */
        this.Max = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Min = 'Min' in params ? params.Min : null;
        this.Max = 'Max' in params ? params.Max : null;

    }
}

/**
 * CancelIsolateDBInstances response structure.
 * @class
 */
class CancelIsolateDBInstancesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of successfully isolated instance ids.
         * @type {Array.<string> || null}
         */
        this.SuccessInstanceIds = null;

        /**
         * Isolation removal failed instance Id list.
         * @type {Array.<string> || null}
         */
        this.FailedInstanceIds = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SuccessInstanceIds = 'SuccessInstanceIds' in params ? params.SuccessInstanceIds : null;
        this.FailedInstanceIds = 'FailedInstanceIds' in params ? params.FailedInstanceIds : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Database view information.
 * @class
 */
class DatabaseView extends  AbstractModel {
    constructor(){
        super();

        /**
         * View name.
         * @type {string || null}
         */
        this.View = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.View = 'View' in params ? params.View : null;

    }
}

/**
 * CancelIsolateDBInstances request structure.
 * @class
 */
class CancelIsolateDBInstancesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of isolated instance ids required.
         * @type {Array.<string> || null}
         */
        this.InstanceIds = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceIds = 'InstanceIds' in params ? params.InstanceIds : null;

    }
}

/**
 * ModifyDBSBackupSetComment request structure.
 * @class
 */
class ModifyDBSBackupSetCommentRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <p>Backup set ID. the value comes from the DescribeDBSBackupSets api response.</p>
         * @type {number || null}
         */
        this.BackupSetId = null;

        /**
         * <P>Backup notes.</p>
         * @type {string || null}
         */
        this.NewBackupName = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.BackupSetId = 'BackupSetId' in params ? params.BackupSetId : null;
        this.NewBackupName = 'NewBackupName' in params ? params.NewBackupName : null;

    }
}

/**
 * Database stored procedure information.
 * @class
 */
class DatabaseProcedure extends  AbstractModel {
    constructor(){
        super();

        /**
         * Stored procedure name.
         * @type {string || null}
         */
        this.Proc = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Proc = 'Proc' in params ? params.Proc : null;

    }
}

/**
 * Cloud database parameter information.
 * @class
 */
class DBParamValue extends  AbstractModel {
    constructor(){
        super();

        /**
         * Parameter name.
         * @type {string || null}
         */
        this.Param = null;

        /**
         * Parameter value.
         * @type {string || null}
         */
        this.Value = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Param = 'Param' in params ? params.Param : null;
        this.Value = 'Value' in params ? params.Value : null;

    }
}

/**
 * Parameter constraints.
 * @class
 */
class ParamConstraint extends  AbstractModel {
    constructor(){
        super();

        /**
         * Constraint type, for example enumeration, interval.
         * @type {string || null}
         */
        this.Type = null;

        /**
         * Lists the available options when the constraint type is enum.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Enum = null;

        /**
         * Value range when the constraint type is section.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {ConstraintRange || null}
         */
        this.Range = null;

        /**
         * Valid values when the constraint type is string.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.String = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Type = 'Type' in params ? params.Type : null;
        this.Enum = 'Enum' in params ? params.Enum : null;

        if (params.Range) {
            let obj = new ConstraintRange();
            obj.deserialize(params.Range)
            this.Range = obj;
        }
        this.String = 'String' in params ? params.String : null;

    }
}

/**
 * ModifyDBParameters request structure.
 * @class
 */
class ModifyDBParametersRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance ID, for example: tdsql3-ow728lmc.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Parameter list, each element is a combination of Param and Value.
         * @type {Array.<DBParamValue> || null}
         */
        this.Params = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;

        if (params.Params) {
            this.Params = new Array();
            for (let z in params.Params) {
                let obj = new DBParamValue();
                obj.deserialize(params.Params[z]);
                this.Params.push(obj);
            }
        }

    }
}

/**
 * ModifyDBInstanceSecurityGroups request structure.
 * @class
 */
class ModifyDBInstanceSecurityGroupsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Instance id.
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * Security group ID list to modify. an array of one or more security group ids.
         * @type {Array.<string> || null}
         */
        this.SecurityGroupIds = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.SecurityGroupIds = 'SecurityGroupIds' in params ? params.SecurityGroupIds : null;

    }
}

/**
 * DeleteDBSBackupSets request structure.
 * @class
 */
class DeleteDBSBackupSetsRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * <p>Instance ID.</p>
         * @type {string || null}
         */
        this.InstanceId = null;

        /**
         * <p>Backup set list. the value comes from the DescribeDBSBackupSets api response.</p>
         * @type {Array.<number> || null}
         */
        this.BackupSetIdList = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.InstanceId = 'InstanceId' in params ? params.InstanceId : null;
        this.BackupSetIdList = 'BackupSetIdList' in params ? params.BackupSetIdList : null;

    }
}

/**
 * Clone instance object.
 * @class
 */
class CloneInstanceModel extends  AbstractModel {
    constructor(){
        super();

        /**
         * Clone task end time.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneEndTime = null;

        /**
         * Clone record ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.CloneId = null;

        /**
         * Clone instance type.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneInsType = null;

        /**
         * Clone instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneInstanceId = null;

        /**
         * Whether the clone instance is deleted.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.CloneInstanceIsDeleted = null;

        /**
         * Task progress of clone.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.CloneProgress = null;

        /**
         * Task start time of the clone.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneStartTime = null;

        /**
         * Task status.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneStatus = null;

        /**
         * Clone time.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneTime = null;

        /**
         * Clone type.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CloneType = null;

        /**
         * Creation time.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.CreateTime = null;

        /**
         * Engine type.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.DBType = null;

        /**
         * Region.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Region = null;

        /**
         * Source instance ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.SourceInstanceId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.CloneEndTime = 'CloneEndTime' in params ? params.CloneEndTime : null;
        this.CloneId = 'CloneId' in params ? params.CloneId : null;
        this.CloneInsType = 'CloneInsType' in params ? params.CloneInsType : null;
        this.CloneInstanceId = 'CloneInstanceId' in params ? params.CloneInstanceId : null;
        this.CloneInstanceIsDeleted = 'CloneInstanceIsDeleted' in params ? params.CloneInstanceIsDeleted : null;
        this.CloneProgress = 'CloneProgress' in params ? params.CloneProgress : null;
        this.CloneStartTime = 'CloneStartTime' in params ? params.CloneStartTime : null;
        this.CloneStatus = 'CloneStatus' in params ? params.CloneStatus : null;
        this.CloneTime = 'CloneTime' in params ? params.CloneTime : null;
        this.CloneType = 'CloneType' in params ? params.CloneType : null;
        this.CreateTime = 'CreateTime' in params ? params.CreateTime : null;
        this.DBType = 'DBType' in params ? params.DBType : null;
        this.Region = 'Region' in params ? params.Region : null;
        this.SourceInstanceId = 'SourceInstanceId' in params ? params.SourceInstanceId : null;

    }
}

module.exports = {
    ArchiveLogInterval: ArchiveLogInterval,
    IsolateDBInstanceRequest: IsolateDBInstanceRequest,
    DescribeFlowRequest: DescribeFlowRequest,
    ModifyDBSBackupSetCommentResponse: ModifyDBSBackupSetCommentResponse,
    ModifyInstanceNameResponse: ModifyInstanceNameResponse,
    ModifyDBInstanceSecurityGroupsResponse: ModifyDBInstanceSecurityGroupsResponse,
    DescribeDBParametersRequest: DescribeDBParametersRequest,
    DescribeDatabaseObjectsResponse: DescribeDatabaseObjectsResponse,
    SecurityGroupBound: SecurityGroupBound,
    CreateDBSBackupResponse: CreateDBSBackupResponse,
    CreateDBSBackupRequest: CreateDBSBackupRequest,
    DestroyInstancesRequest: DestroyInstancesRequest,
    DescribeDBSecurityGroupsRequest: DescribeDBSecurityGroupsRequest,
    ModifyDBParametersResponse: ModifyDBParametersResponse,
    ModifyInstanceNameRequest: ModifyInstanceNameRequest,
    ParamDesc: ParamDesc,
    ModifyAutoRenewFlagRequest: ModifyAutoRenewFlagRequest,
    ModifyDBSBackupPolicyResponse: ModifyDBSBackupPolicyResponse,
    DescribeDBSCloneInstancesResponse: DescribeDBSCloneInstancesResponse,
    DescribeDBSecurityGroupsResponse: DescribeDBSecurityGroupsResponse,
    BackupPolicyModelInput: BackupPolicyModelInput,
    DatabaseFunction: DatabaseFunction,
    ModifyDBSBackupPolicyRequest: ModifyDBSBackupPolicyRequest,
    DescribeDBSCloneInstancesRequest: DescribeDBSCloneInstancesRequest,
    DescribeDatabaseObjectsRequest: DescribeDatabaseObjectsRequest,
    DescribeDBSAvailableRecoveryTimeResponse: DescribeDBSAvailableRecoveryTimeResponse,
    ModifyAutoRenewFlagResponse: ModifyAutoRenewFlagResponse,
    DestroyInstancesResponse: DestroyInstancesResponse,
    DescribeDBParametersResponse: DescribeDBParametersResponse,
    SecurityGroup: SecurityGroup,
    IsolateDBInstanceResponse: IsolateDBInstanceResponse,
    DescribeDBSAvailableRecoveryTimeRequest: DescribeDBSAvailableRecoveryTimeRequest,
    DatabaseTable: DatabaseTable,
    DeleteDBSBackupSetsResponse: DeleteDBSBackupSetsResponse,
    DescribeFlowResponse: DescribeFlowResponse,
    ConstraintRange: ConstraintRange,
    CancelIsolateDBInstancesResponse: CancelIsolateDBInstancesResponse,
    DatabaseView: DatabaseView,
    CancelIsolateDBInstancesRequest: CancelIsolateDBInstancesRequest,
    ModifyDBSBackupSetCommentRequest: ModifyDBSBackupSetCommentRequest,
    DatabaseProcedure: DatabaseProcedure,
    DBParamValue: DBParamValue,
    ParamConstraint: ParamConstraint,
    ModifyDBParametersRequest: ModifyDBParametersRequest,
    ModifyDBInstanceSecurityGroupsRequest: ModifyDBInstanceSecurityGroupsRequest,
    DeleteDBSBackupSetsRequest: DeleteDBSBackupSetsRequest,
    CloneInstanceModel: CloneInstanceModel,

}
