/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * Token deferral request
 * @class
 */
class ApplyEmbedTokenInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Request result.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {boolean || null}
         */
        this.Result = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Result = 'Result' in params ? params.Result : null;

    }
}

/**
 * ApplyEmbedInterval response structure.
 * @class
 */
class ApplyEmbedIntervalResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Custom error information object.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {ErrorInfo || null}
         */
        this.ErrorInfo = null;

        /**
         * Additional parameters.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Extra = null;

        /**
         * Result data.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {ApplyEmbedTokenInfo || null}
         */
        this.Data = null;

        /**
         * Result description.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Msg = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.ErrorInfo) {
            let obj = new ErrorInfo();
            obj.deserialize(params.ErrorInfo)
            this.ErrorInfo = obj;
        }
        this.Extra = 'Extra' in params ? params.Extra : null;

        if (params.Data) {
            let obj = new ApplyEmbedTokenInfo();
            obj.deserialize(params.Data)
            this.Data = obj;
        }
        this.Msg = 'Msg' in params ? params.Msg : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreateDatasource request structure.
 * @class
 */
class CreateDatasourceRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * HOST
         * @type {string || null}
         */
        this.DbHost = null;

        /**
         * Port.
         * @type {number || null}
         */
        this.DbPort = null;

        /**
         * The backend provides dictionaries: domain type. 1. Tencent Cloud, 2. local.
         * @type {string || null}
         */
        this.ServiceType = null;

        /**
         * Drive.
         * @type {string || null}
         */
        this.DbType = null;

        /**
         * Database encoding.
         * @type {string || null}
         */
        this.Charset = null;

        /**
         * Username.
         * @type {string || null}
         */
        this.DbUser = null;

        /**
         * Password.
         * @type {string || null}
         */
        this.DbPwd = null;

        /**
         * Database name.
         * @type {string || null}
         */
        this.DbName = null;

        /**
         * Database alias.
         * @type {string || null}
         */
        this.SourceName = null;

        /**
         * Project ID.
         * @type {number || null}
         */
        this.ProjectId = null;

        /**
         * Catalog value.
         * @type {string || null}
         */
        this.Catalog = null;

        /**
         * Third-party data source identifier.
         * @type {string || null}
         */
        this.DataOrigin = null;

        /**
         * Third-party project ID.
         * @type {string || null}
         */
        this.DataOriginProjectId = null;

        /**
         * Third-party data source ID.
         * @type {string || null}
         */
        this.DataOriginDatasourceId = null;

        /**
         * Extension parameter.
         * @type {string || null}
         */
        this.ExtraParam = null;

        /**
         * Unified identifier of the Tencent Cloud VPC.
         * @type {string || null}
         */
        this.UniqVpcId = null;

        /**
         * VPC IP address.
         * @type {string || null}
         */
        this.Vip = null;

        /**
         * VPC port.
         * @type {string || null}
         */
        this.Vport = null;

        /**
         * Tencent Cloud VPC identifier.
         * @type {string || null}
         */
        this.VpcId = null;

        /**
         * Operation permission limitation.
         * @type {Array.<string> || null}
         */
        this.OperationAuthLimit = null;

        /**
         * Enables VPC.
         * @type {boolean || null}
         */
        this.UseVPC = null;

        /**
         * Region.
         * @type {string || null}
         */
        this.RegionId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.DbHost = 'DbHost' in params ? params.DbHost : null;
        this.DbPort = 'DbPort' in params ? params.DbPort : null;
        this.ServiceType = 'ServiceType' in params ? params.ServiceType : null;
        this.DbType = 'DbType' in params ? params.DbType : null;
        this.Charset = 'Charset' in params ? params.Charset : null;
        this.DbUser = 'DbUser' in params ? params.DbUser : null;
        this.DbPwd = 'DbPwd' in params ? params.DbPwd : null;
        this.DbName = 'DbName' in params ? params.DbName : null;
        this.SourceName = 'SourceName' in params ? params.SourceName : null;
        this.ProjectId = 'ProjectId' in params ? params.ProjectId : null;
        this.Catalog = 'Catalog' in params ? params.Catalog : null;
        this.DataOrigin = 'DataOrigin' in params ? params.DataOrigin : null;
        this.DataOriginProjectId = 'DataOriginProjectId' in params ? params.DataOriginProjectId : null;
        this.DataOriginDatasourceId = 'DataOriginDatasourceId' in params ? params.DataOriginDatasourceId : null;
        this.ExtraParam = 'ExtraParam' in params ? params.ExtraParam : null;
        this.UniqVpcId = 'UniqVpcId' in params ? params.UniqVpcId : null;
        this.Vip = 'Vip' in params ? params.Vip : null;
        this.Vport = 'Vport' in params ? params.Vport : null;
        this.VpcId = 'VpcId' in params ? params.VpcId : null;
        this.OperationAuthLimit = 'OperationAuthLimit' in params ? params.OperationAuthLimit : null;
        this.UseVPC = 'UseVPC' in params ? params.UseVPC : null;
        this.RegionId = 'RegionId' in params ? params.RegionId : null;

    }
}

/**
 * CreateDatasource response structure.
 * @class
 */
class CreateDatasourceResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Custom error information object.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {ErrorInfo || null}
         */
        this.ErrorInfo = null;

        /**
         * Data source ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {IdDTO || null}
         */
        this.Data = null;

        /**
         * Additional information.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Extra = null;

        /**
         * Prompt.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.Msg = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.ErrorInfo) {
            let obj = new ErrorInfo();
            obj.deserialize(params.ErrorInfo)
            this.ErrorInfo = obj;
        }

        if (params.Data) {
            let obj = new IdDTO();
            obj.deserialize(params.Data)
            this.Data = obj;
        }
        this.Extra = 'Extra' in params ? params.Extra : null;
        this.Msg = 'Msg' in params ? params.Msg : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * ApplyEmbedInterval request structure.
 * @class
 */
class ApplyEmbedIntervalRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Shares the project ID. Required.
         * @type {number || null}
         */
        this.ProjectId = null;

        /**
         * Shares the page ID. This field is empty (0) for embedding a dashboard and is not passed for embedding ChatBI.

         * @type {number || null}
         */
        this.PageId = null;

        /**
         * Token requiring extension.
         * @type {string || null}
         */
        this.BIToken = null;

        /**
         * Alternate field.
         * @type {string || null}
         */
        this.ExtraParam = null;

        /**
         * embed: page/dashboard embedding.
chatBIEmbed: ChatBI embedding.
         * @type {string || null}
         */
        this.Intention = null;

        /**
         * panel: dashboard; page: page.
project, during ChatBI embedding.
         * @type {string || null}
         */
        this.Scope = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ProjectId = 'ProjectId' in params ? params.ProjectId : null;
        this.PageId = 'PageId' in params ? params.PageId : null;
        this.BIToken = 'BIToken' in params ? params.BIToken : null;
        this.ExtraParam = 'ExtraParam' in params ? params.ExtraParam : null;
        this.Intention = 'Intention' in params ? params.Intention : null;
        this.Scope = 'Scope' in params ? params.Scope : null;

    }
}

/**
 * Object containing only ID
 * @class
 */
class IdDTO extends  AbstractModel {
    constructor(){
        super();

        /**
         * Request ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.Id = null;

        /**
         * key
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.AccessKey = null;

        /**
         * id
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.ProjectId = null;

        /**
         * Transaction ID.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.TranId = null;

        /**
         * Transaction status.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {number || null}
         */
        this.TranStatus = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Id = 'Id' in params ? params.Id : null;
        this.AccessKey = 'AccessKey' in params ? params.AccessKey : null;
        this.ProjectId = 'ProjectId' in params ? params.ProjectId : null;
        this.TranId = 'TranId' in params ? params.TranId : null;
        this.TranStatus = 'TranStatus' in params ? params.TranStatus : null;

    }
}

/**
 * Custom error information object
 * @class
 */
class ErrorInfo extends  AbstractModel {
    constructor(){
        super();

        /**
         * Error description field.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ErrorTip = null;

        /**
         * Original exception message.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ErrorMessage = null;

        /**
         * Error level field.
ERROR
WARN
INFO
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ErrorLevel = null;

        /**
         * Documentation link.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.DocLink = null;

        /**
         * Quick start guide.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.FAQ = null;

        /**
         * Reserved field 1.
Note: This field may return null, indicating that no valid values can be obtained.
         * @type {string || null}
         */
        this.ReservedField = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.ErrorTip = 'ErrorTip' in params ? params.ErrorTip : null;
        this.ErrorMessage = 'ErrorMessage' in params ? params.ErrorMessage : null;
        this.ErrorLevel = 'ErrorLevel' in params ? params.ErrorLevel : null;
        this.DocLink = 'DocLink' in params ? params.DocLink : null;
        this.FAQ = 'FAQ' in params ? params.FAQ : null;
        this.ReservedField = 'ReservedField' in params ? params.ReservedField : null;

    }
}

module.exports = {
    ApplyEmbedTokenInfo: ApplyEmbedTokenInfo,
    ApplyEmbedIntervalResponse: ApplyEmbedIntervalResponse,
    CreateDatasourceRequest: CreateDatasourceRequest,
    CreateDatasourceResponse: CreateDatasourceResponse,
    ApplyEmbedIntervalRequest: ApplyEmbedIntervalRequest,
    IdDTO: IdDTO,
    ErrorInfo: ErrorInfo,

}
