/*
 * Copyright (c) 2018 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const AbstractModel = require("../../common/abstract_model");

/**
 * ModifyGlossaryEntries request structure.
 * @class
 */
class ModifyGlossaryEntriesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID. Obtain through the API DescribeGlossaries.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Terminology entry list. At a time 200.
         * @type {Array.<ModifyGlossaryEntryInput> || null}
         */
        this.Entries = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new ModifyGlossaryEntryInput();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }

    }
}

/**
 * CreateGlossary request structure.
 * @class
 */
class CreateGlossaryRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology library name. Maximum 50 characters.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Source language code. Maximum 16 characters, such as zh (Chinese), en (English).
         * @type {string || null}
         */
        this.Source = null;

        /**
         * Target language code. Maximum 16 characters, such as zh (Chinese), en (English).
         * @type {string || null}
         */
        this.Target = null;

        /**
         * Termbase description. Maximum 255 characters.
         * @type {string || null}
         */
        this.Description = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;
        this.Source = 'Source' in params ? params.Source : null;
        this.Target = 'Target' in params ? params.Target : null;
        this.Description = 'Description' in params ? params.Description : null;

    }
}

/**
 * DescribeGlossaryEntries response structure.
 * @class
 */
class DescribeGlossaryEntriesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology entry list.
         * @type {Array.<GlossaryEntryItem> || null}
         */
        this.Entries = null;

        /**
         * Total number of eligible terminology entries.
         * @type {number || null}
         */
        this.Total = null;

        /**
         * Current page.
         * @type {number || null}
         */
        this.Page = null;

        /**
         * Size per page
         * @type {number || null}
         */
        this.PageSize = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new GlossaryEntryItem();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }
        this.Total = 'Total' in params ? params.Total : null;
        this.Page = 'Page' in params ? params.Page : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DeleteGlossary request structure.
 * @class
 */
class DeleteGlossaryRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID. Obtain through the API DescribeGlossaries.
         * @type {string || null}
         */
        this.GlossaryId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;

    }
}

/**
 * DescribeGlossaryEntries request structure.
 * @class
 */
class DescribeGlossaryEntriesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID. Obtain through the API DescribeGlossaries.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Page number. Default is 1.
         * @type {number || null}
         */
        this.Page = null;

        /**
         * Size per page. The default value is 20, and the maximum value is 200.
         * @type {number || null}
         */
        this.PageSize = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;
        this.Page = 'Page' in params ? params.Page : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;

    }
}

/**
 * DescribeGlossaries request structure.
 * @class
 */
class DescribeGlossariesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Number of returned results. Defaults to 20, maximum value is 100.
         * @type {number || null}
         */
        this.Limit = null;

        /**
         * Offset. Default value: 0.
         * @type {number || null}
         */
        this.Offset = null;

        /**
         * Filter condition list. Supported filter fields: GlossaryId (Termbase ID), Name, Source (source language code), Target (target language code).
         * @type {Array.<RequestFilter> || null}
         */
        this.Filters = null;

        /**
         * Sorting condition list. Supported sorting fields: CreatedTime (creation time), UpdatedTime (last update time).
         * @type {Array.<RequestSort> || null}
         */
        this.Sorts = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Limit = 'Limit' in params ? params.Limit : null;
        this.Offset = 'Offset' in params ? params.Offset : null;

        if (params.Filters) {
            this.Filters = new Array();
            for (let z in params.Filters) {
                let obj = new RequestFilter();
                obj.deserialize(params.Filters[z]);
                this.Filters.push(obj);
            }
        }

        if (params.Sorts) {
            this.Sorts = new Array();
            for (let z in params.Sorts) {
                let obj = new RequestSort();
                obj.deserialize(params.Sorts[z]);
                this.Sorts.push(obj);
            }
        }

    }
}

/**
 * Filter criteria
 * @class
 */
class RequestFilter extends  AbstractModel {
    constructor(){
        super();

        /**
         * Filter field name.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Filter operator. Values: EXACT (exact match), FUZZY (fuzzy matching), NOT (exclusion).
         * @type {string || null}
         */
        this.Op = null;

        /**
         * Filter value list. Supports up to 10.
         * @type {Array.<string> || null}
         */
        this.Values = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;
        this.Op = 'Op' in params ? params.Op : null;
        this.Values = 'Values' in params ? params.Values : null;

    }
}

/**
 * DeleteGlossaryEntries request structure.
 * @class
 */
class DeleteGlossaryEntriesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID. Obtain through the API DescribeGlossaries.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Terminology entry list to be deleted. At a time 200.
         * @type {Array.<DeleteGlossaryEntryInput> || null}
         */
        this.Entries = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new DeleteGlossaryEntryInput();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }

    }
}

/**
 * CreateGlossaryEntries response structure.
 * @class
 */
class CreateGlossaryEntriesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * List of successfully created terminology entries.
         * @type {Array.<GlossaryEntryItem> || null}
         */
        this.Entries = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new GlossaryEntryItem();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Delete terminology entry
 * @class
 */
class DeleteGlossaryEntryInput extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology entry ID. Obtain through the API DescribeGlossaryEntries.
         * @type {string || null}
         */
        this.EntryId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.EntryId = 'EntryId' in params ? params.EntryId : null;

    }
}

/**
 * Terminology entry detail
 * @class
 */
class GlossaryEntryItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology entry ID.
         * @type {string || null}
         */
        this.EntryId = null;

        /**
         * Source language terminology.
         * @type {string || null}
         */
        this.SourceTerm = null;

        /**
         * Target language terminology.
         * @type {string || null}
         */
        this.TargetTerm = null;

        /**
         * Last update time. Unix timestamp (ms).
         * @type {number || null}
         */
        this.UpdatedAt = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.EntryId = 'EntryId' in params ? params.EntryId : null;
        this.SourceTerm = 'SourceTerm' in params ? params.SourceTerm : null;
        this.TargetTerm = 'TargetTerm' in params ? params.TargetTerm : null;
        this.UpdatedAt = 'UpdatedAt' in params ? params.UpdatedAt : null;

    }
}

/**
 * DeleteGlossary response structure.
 * @class
 */
class DeleteGlossaryResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * CreateGlossaryEntries request structure.
 * @class
 */
class CreateGlossaryEntriesRequest extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID. Obtain through the API DescribeGlossaries.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Terminology entry list. At a time 100.
         * @type {Array.<GlossaryEntryInput> || null}
         */
        this.Entries = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new GlossaryEntryInput();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }

    }
}

/**
 * Sort criteria
 * @class
 */
class RequestSort extends  AbstractModel {
    constructor(){
        super();

        /**
         * Sorting field name.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Sorting order. Value: ASC (ascending), DESC (descending).
         * @type {string || null}
         */
        this.Order = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.Name = 'Name' in params ? params.Name : null;
        this.Order = 'Order' in params ? params.Order : null;

    }
}

/**
 * ModifyGlossaryEntries response structure.
 * @class
 */
class ModifyGlossaryEntriesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology entry list after modification.
         * @type {Array.<GlossaryEntryItem> || null}
         */
        this.Entries = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Entries) {
            this.Entries = new Array();
            for (let z in params.Entries) {
                let obj = new GlossaryEntryItem();
                obj.deserialize(params.Entries[z]);
                this.Entries.push(obj);
            }
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Modify terminology entry
 * @class
 */
class ModifyGlossaryEntryInput extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology entry ID. Obtain through the API DescribeGlossaryEntries.
         * @type {string || null}
         */
        this.EntryId = null;

        /**
         * Source language terminology. Maximum 1000 characters. If not passed, remain unchanged.
         * @type {string || null}
         */
        this.SourceTerm = null;

        /**
         * Target language terminology. Maximum 1000 characters. Remain unchanged if not passed.
         * @type {string || null}
         */
        this.TargetTerm = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.EntryId = 'EntryId' in params ? params.EntryId : null;
        this.SourceTerm = 'SourceTerm' in params ? params.SourceTerm : null;
        this.TargetTerm = 'TargetTerm' in params ? params.TargetTerm : null;

    }
}

/**
 * DeleteGlossaryEntries response structure.
 * @class
 */
class DeleteGlossaryEntriesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * DescribeGlossaries response structure.
 * @class
 */
class DescribeGlossariesResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Terminology repository list.
         * @type {Array.<GlossaryItem> || null}
         */
        this.Items = null;

        /**
         * Total number of eligible terminology repositories.
         * @type {number || null}
         */
        this.TotalCount = null;

        /**
         * Current page.
         * @type {number || null}
         */
        this.Current = null;

        /**
         * Size per page
         * @type {number || null}
         */
        this.PageSize = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }

        if (params.Items) {
            this.Items = new Array();
            for (let z in params.Items) {
                let obj = new GlossaryItem();
                obj.deserialize(params.Items[z]);
                this.Items.push(obj);
            }
        }
        this.TotalCount = 'TotalCount' in params ? params.TotalCount : null;
        this.Current = 'Current' in params ? params.Current : null;
        this.PageSize = 'PageSize' in params ? params.PageSize : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

/**
 * Termbase detail
 * @class
 */
class GlossaryItem extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Terminology repository name.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Repository description.
         * @type {string || null}
         */
        this.Description = null;

        /**
         * Source language code.
         * @type {string || null}
         */
        this.Source = null;

        /**
         * Target language code.
         * @type {string || null}
         */
        this.Target = null;

        /**
         * Creation time.
         * @type {string || null}
         */
        this.CreatedTime = null;

        /**
         * Update time.
         * @type {string || null}
         */
        this.UpdatedTime = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;
        this.Name = 'Name' in params ? params.Name : null;
        this.Description = 'Description' in params ? params.Description : null;
        this.Source = 'Source' in params ? params.Source : null;
        this.Target = 'Target' in params ? params.Target : null;
        this.CreatedTime = 'CreatedTime' in params ? params.CreatedTime : null;
        this.UpdatedTime = 'UpdatedTime' in params ? params.UpdatedTime : null;

    }
}

/**
 * Create terminology entry
 * @class
 */
class GlossaryEntryInput extends  AbstractModel {
    constructor(){
        super();

        /**
         * Source language terminology. Maximum 1000 characters.
         * @type {string || null}
         */
        this.SourceTerm = null;

        /**
         * Target language terminology. Maximum 1000 characters.
         * @type {string || null}
         */
        this.TargetTerm = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.SourceTerm = 'SourceTerm' in params ? params.SourceTerm : null;
        this.TargetTerm = 'TargetTerm' in params ? params.TargetTerm : null;

    }
}

/**
 * CreateGlossary response structure.
 * @class
 */
class CreateGlossaryResponse extends  AbstractModel {
    constructor(){
        super();

        /**
         * Termbase ID.
         * @type {string || null}
         */
        this.GlossaryId = null;

        /**
         * Terminology repository name.
         * @type {string || null}
         */
        this.Name = null;

        /**
         * Creation time. Unix timestamp (ms).
         * @type {number || null}
         */
        this.CreatedAt = null;

        /**
         * The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
         * @type {string || null}
         */
        this.RequestId = null;

    }

    /**
     * @private
     */
    deserialize(params) {
        if (!params) {
            return;
        }
        this.GlossaryId = 'GlossaryId' in params ? params.GlossaryId : null;
        this.Name = 'Name' in params ? params.Name : null;
        this.CreatedAt = 'CreatedAt' in params ? params.CreatedAt : null;
        this.RequestId = 'RequestId' in params ? params.RequestId : null;

    }
}

module.exports = {
    ModifyGlossaryEntriesRequest: ModifyGlossaryEntriesRequest,
    CreateGlossaryRequest: CreateGlossaryRequest,
    DescribeGlossaryEntriesResponse: DescribeGlossaryEntriesResponse,
    DeleteGlossaryRequest: DeleteGlossaryRequest,
    DescribeGlossaryEntriesRequest: DescribeGlossaryEntriesRequest,
    DescribeGlossariesRequest: DescribeGlossariesRequest,
    RequestFilter: RequestFilter,
    DeleteGlossaryEntriesRequest: DeleteGlossaryEntriesRequest,
    CreateGlossaryEntriesResponse: CreateGlossaryEntriesResponse,
    DeleteGlossaryEntryInput: DeleteGlossaryEntryInput,
    GlossaryEntryItem: GlossaryEntryItem,
    DeleteGlossaryResponse: DeleteGlossaryResponse,
    CreateGlossaryEntriesRequest: CreateGlossaryEntriesRequest,
    RequestSort: RequestSort,
    ModifyGlossaryEntriesResponse: ModifyGlossaryEntriesResponse,
    ModifyGlossaryEntryInput: ModifyGlossaryEntryInput,
    DeleteGlossaryEntriesResponse: DeleteGlossaryEntriesResponse,
    DescribeGlossariesResponse: DescribeGlossariesResponse,
    GlossaryItem: GlossaryItem,
    GlossaryEntryInput: GlossaryEntryInput,
    CreateGlossaryResponse: CreateGlossaryResponse,

}
